import type { ModuleQA } from "./types";

export const stacksQA: ModuleQA = {
  moduleSlug: "stacks",
  moduleTitle: "Stacks",
  faqPath: "/stacks/faq",
  interviewPath: "/stacks/interview",
  faqs: [
    {
      category: "Concepts",
      q: "What is a stack and why is it called LIFO?",
      answer: [
        "A stack is a linear container where all insertions and removals happen at one end — the 'top'. The last item pushed is the first one popped, hence Last-In-First-Out.",
        "Think of a pile of plates: you can only touch the top plate. This ordering is exactly what the CPU's call stack, expression parsers, and undo buffers need.",
      ],
      code: `stack = []\nstack.append(10)   # push\nstack.append(20)\nstack.pop()        # 20  (LIFO)`,
      related: [{ label: "Overview", to: "/modules/stacks" }],
    },
    {
      category: "Concepts",
      q: "What are the core stack operations?",
      answer: [
        "Push (add to top), Pop (remove from top), Peek/Top (read without removing), isEmpty (test), and often Size. All five run in O(1) on either a list-backed or linked-list-backed stack.",
      ],
      time: "push · pop · peek · isEmpty · size — all O(1)",
    },
    {
      category: "Concepts",
      q: "Stack vs Array — how are they different?",
      answer: [
        "An array supports random access at any index; a stack restricts you to touching the top. That restriction is what makes stacks a great abstraction — the API is small and impossible to misuse.",
        "Under the hood, a stack is usually implemented on top of an array (Python list) or a singly linked list; the wrapper just enforces the LIFO discipline.",
      ],
    },
    {
      category: "Concepts",
      q: "What are Stack Overflow and Stack Underflow?",
      answer: [
        "Overflow: pushing onto a full stack — only possible with a bounded/fixed-capacity stack. Python's list-backed stack grows dynamically, so overflow is really 'MemoryError'.",
        "Underflow: popping (or peeking) an empty stack. Python raises `IndexError`; C-style implementations often return a sentinel.",
        "Recursion depth is another form of overflow: every function call pushes a frame onto the interpreter's call stack. Python's default limit is 1000 frames.",
      ],
      mistake: "Assuming `list.pop()` on an empty list returns None — it raises IndexError.",
    },
    {
      category: "Concepts",
      q: "What is a stack pointer?",
      answer: [
        "In a fixed-capacity array-backed stack, the stack pointer is the index of the current top (often called `top` or `sp`). Push increments it, pop decrements it. `sp == -1` means empty.",
        "In hardware, the CPU maintains a real register called the stack pointer that points at the top of the call stack in memory.",
      ],
      code: `class ArrayStack:\n    def __init__(self, cap):\n        self.buf = [None] * cap; self.sp = -1\n    def push(self, x):\n        self.sp += 1; self.buf[self.sp] = x\n    def pop(self):\n        x = self.buf[self.sp]; self.sp -= 1; return x`,
    },
    {
      category: "Operations",
      q: "How do I implement a stack using a Python list?",
      answer: [
        "Use `append` to push and `pop()` (no argument) to pop — both are amortised O(1). `list[-1]` is the peek.",
        "Never use `insert(0, x)` and `pop(0)` — those shift every element and run in O(n).",
      ],
      code: `stack = []\nstack.append(x)   # push  — O(1)*\nstack.pop()       # pop   — O(1)\nstack[-1]         # peek  — O(1)`,
    },
    {
      category: "Operations",
      q: "How do I implement a stack using a linked list?",
      answer: [
        "Keep the top of the stack at the head of a singly linked list. Push allocates a new head; pop returns and unlinks the current head.",
      ],
      code: `class Node:\n    def __init__(self, v, nxt=None): self.v, self.next = v, nxt\nclass Stack:\n    def __init__(self): self.top = None\n    def push(self, x): self.top = Node(x, self.top)\n    def pop(self):\n        n = self.top; self.top = n.next; return n.v`,
      time: "push · pop — O(1)",
      related: [
        { label: "Linked Lists · Foundations", to: "/linked-lists/foundations/introduction" },
      ],
    },
    {
      category: "Operations",
      q: "How do I implement a stack using two queues?",
      answer: [
        "Push into queue `q1`. Pop by moving every element except the last from `q1` into `q2`, popping the last (which was the most recent push), then swapping the queue references.",
        "Amortised O(n) per pop, O(1) per push. The reverse question — queue with two stacks — is much more common in interviews.",
      ],
      code: `from collections import deque\nclass Stack:\n    def __init__(self):\n        self.q1, self.q2 = deque(), deque()\n    def push(self, x): self.q1.append(x)\n    def pop(self):\n        while len(self.q1) > 1:\n            self.q2.append(self.q1.popleft())\n        x = self.q1.popleft()\n        self.q1, self.q2 = self.q2, self.q1\n        return x`,
    },
    {
      category: "Operations",
      q: "How do I reverse a string using a stack?",
      answer: [
        "Push every character onto a stack, then pop them off — you'll get the string back-to-front.",
        "In Python, `s[::-1]` is faster and idiomatic. The stack version is here to illustrate LIFO, not to compete with the slice.",
      ],
      code: `def reverse(s):\n    st = list(s)\n    return "".join(st.pop() for _ in range(len(st)))`,
      time: "O(n)",
      space: "O(n)",
    },
    {
      category: "Operations",
      q: "How do I reverse a stack using recursion?",
      answer: [
        "Two-phase recursion: pop everything to unwind the stack, then insert each popped value at the bottom on the way back up. `insert_at_bottom` is itself recursive.",
      ],
      code: `def insert_at_bottom(st, x):\n    if not st:\n        st.append(x); return\n    top = st.pop()\n    insert_at_bottom(st, x)\n    st.append(top)\n\ndef reverse_stack(st):\n    if not st: return\n    top = st.pop()\n    reverse_stack(st)\n    insert_at_bottom(st, top)`,
      time: "O(n²)",
      space: "O(n) recursion stack",
    },
    {
      category: "Design",
      q: "How do I implement a stack that supports getMin() in O(1)?",
      answer: [
        "Track a second stack of running minimums. Every push compares with the current min; every pop pops both stacks in lock-step. Peek `min_stack[-1]` for the current min in O(1).",
      ],
      code: `class MinStack:\n    def __init__(self): self.st, self.mn = [], []\n    def push(self, x):\n        self.st.append(x)\n        self.mn.append(x if not self.mn else min(x, self.mn[-1]))\n    def pop(self):\n        self.st.pop(); self.mn.pop()\n    def top(self):  return self.st[-1]\n    def getMin(self): return self.mn[-1]`,
      related: [{ label: "Interview · MinStack", to: "/stacks/interview" }],
    },
    {
      category: "Design",
      q: "How do I design a stack that rejects duplicate values?",
      answer: [
        "Pair the stack with a hash set of currently-contained values. `push(x)` becomes a no-op (or raises) when `x in seen`; `pop()` removes from both.",
      ],
      code: `class UniqueStack:\n    def __init__(self): self.st, self.seen = [], set()\n    def push(self, x):\n        if x in self.seen: return False\n        self.st.append(x); self.seen.add(x); return True\n    def pop(self):\n        x = self.st.pop(); self.seen.remove(x); return x`,
    },
    {
      category: "Memory",
      q: "What is the call stack and why can it overflow?",
      answer: [
        "Every function call pushes a frame containing its locals, arguments, and return address. Returning pops the frame. Recursion accumulates frames — Python caps this at 1000 by default.",
        "Deep-recursion algorithms (naive tree DFS, deep linked-list reverse) can hit `RecursionError`. Convert to iteration with an explicit stack when depth is unbounded.",
      ],
      code: `import sys\nsys.setrecursionlimit(10_000)   # bump if you really must recurse deeper`,
      mistake:
        "Bumping the recursion limit as a fix — the underlying OS thread stack can still overflow (~10 000 Python frames on most platforms).",
    },
    {
      category: "Practical",
      q: "How do I check for balanced parentheses?",
      answer: [
        "Push every opener; on a closer, pop and confirm the pair matches. If the stack is empty on a closer, or non-empty at the end, the string is invalid.",
      ],
      code: `def valid(s):\n    pairs = {')':'(', ']':'[', '}':'{'}\n    st = []\n    for c in s:\n        if c in "([{": st.append(c)\n        elif not st or st.pop() != pairs[c]: return False\n    return not st`,
      time: "O(n)",
      space: "O(n)",
      related: [{ label: "Interview · Valid Parentheses", to: "/stacks/interview" }],
    },
    {
      category: "Practical",
      q: "What are common real-world uses of stacks?",
      answer: [
        "• Function call stack in every programming language.",
        "• Expression evaluation and syntax parsing (compilers, calculators).",
        "• Undo/redo buffers in editors.",
        "• Backtracking (DFS on trees and graphs, N-queens, Sudoku solvers).",
        "• Browser history's back button.",
      ],
    },
  ],

  interview: [
    // ── Theory ────────────────────────────────────────────────────────────
    {
      id: "st-i-1",
      title: "Explain the LIFO principle with an example",
      category: "Theory",
      difficulty: "Beginner",
      estMin: 3,
      tags: ["fundamentals"],
      explanation: [
        "LIFO = Last-In-First-Out. The last thing pushed is the first thing popped. Everyday example: a stack of plates or the browser 'Back' button.",
      ],
    },
    {
      id: "st-i-2",
      title: "Applications of a stack",
      category: "Theory",
      difficulty: "Beginner",
      estMin: 3,
      tags: ["applications"],
      explanation: [
        "Function call stack; expression parsing; undo/redo; backtracking (DFS, N-queens); browser history; syntax matching. Any workflow that must 'unwind' recent state naturally maps to a stack.",
      ],
    },
    {
      id: "st-i-3",
      title: "Stack Overflow vs Stack Underflow",
      category: "Theory",
      difficulty: "Beginner",
      estMin: 3,
      tags: ["edge"],
      explanation: [
        "Overflow: pushing past capacity on a bounded stack, or exceeding Python's recursion depth.",
        "Underflow: popping/peeking an empty stack. Python raises `IndexError`.",
      ],
    },
    {
      id: "st-i-4",
      title: "Purpose of the stack pointer",
      category: "Theory",
      difficulty: "Beginner",
      estMin: 3,
      tags: ["internals"],
      explanation: [
        "It marks the current top. On push it advances; on pop it retreats. Whether it's a variable in a class or an actual CPU register, the role is identical: know where 'top' lives right now.",
      ],
    },
    {
      id: "st-i-5",
      title: "Stack vs Array — key differences",
      category: "Conceptual",
      difficulty: "Beginner",
      estMin: 4,
      tags: ["comparison"],
      explanation: [
        "An array supports arbitrary index access; a stack restricts you to the top. Stacks are usually implemented on top of an array — the difference is the discipline, not the underlying storage.",
      ],
    },

    // ── Implementation ────────────────────────────────────────────────────
    {
      id: "st-i-6",
      title: "Implement a stack with push, pop, peek, and display",
      category: "Coding",
      difficulty: "Beginner",
      estMin: 10,
      tags: ["must-do", "impl"],
      explanation: [
        "Wrap a Python list. All five operations become one-liners: `append`, `pop`, `list[-1]`, `not list`, iteration.",
      ],
      code: `class Stack:\n    def __init__(self): self._d = []\n    def push(self, x): self._d.append(x)\n    def pop(self): return self._d.pop()\n    def peek(self): return self._d[-1]\n    def is_empty(self): return not self._d\n    def display(self): return list(reversed(self._d))`,
      time: "O(1) per op",
      space: "O(n)",
    },
    {
      id: "st-i-7",
      title: "Implement a stack using a linked list",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 15,
      tags: ["linked-list"],
      explanation: [
        "Keep the top of the stack at the head of a singly linked list — push prepends, pop unlinks the head. Both O(1).",
      ],
      code: `class Node:\n    def __init__(self, v, nxt=None): self.v, self.next = v, nxt\nclass Stack:\n    def __init__(self): self.top = None\n    def push(self, x): self.top = Node(x, self.top)\n    def pop(self):\n        n = self.top; self.top = n.next; return n.v`,
      time: "O(1)",
      space: "O(n)",
      relatedLessons: [
        { label: "Linked Lists · Foundations", to: "/linked-lists/foundations/introduction" },
      ],
    },
    {
      id: "st-i-8",
      title: "Implement a stack using two queues",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 20,
      tags: ["queue", "trick"],
      explanation: [
        "Two queues q1, q2. Push into q1. To pop, move all-but-one from q1 into q2, pop the remaining, then swap. Amortised O(n) per pop.",
      ],
      code: `from collections import deque\nclass Stack:\n    def __init__(self): self.q1, self.q2 = deque(), deque()\n    def push(self, x): self.q1.append(x)\n    def pop(self):\n        while len(self.q1) > 1: self.q2.append(self.q1.popleft())\n        x = self.q1.popleft(); self.q1, self.q2 = self.q2, self.q1; return x`,
      time: "push O(1) · pop O(n)",
      space: "O(n)",
      leetcode: {
        title: "225 · Implement Stack using Queues",
        url: "https://leetcode.com/problems/implement-stack-using-queues/",
        difficulty: "Easy",
      },
    },
    {
      id: "st-i-9",
      title: "Design a stack that rejects duplicate values",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 15,
      tags: ["hash"],
      explanation: [
        "Maintain a companion set. Push checks membership first; pop removes from both structures.",
      ],
      code: `class UniqueStack:\n    def __init__(self): self.st, self.seen = [], set()\n    def push(self, x):\n        if x in self.seen: return False\n        self.st.append(x); self.seen.add(x); return True\n    def pop(self):\n        x = self.st.pop(); self.seen.remove(x); return x`,
      time: "O(1) per op",
      space: "O(n)",
    },

    // ── Algorithms ────────────────────────────────────────────────────────
    {
      id: "st-i-10",
      title: "Reverse a string using a stack",
      category: "Coding",
      difficulty: "Beginner",
      estMin: 5,
      tags: ["classic"],
      explanation: [
        "Push each character; pop into a new string. Straightforward LIFO demo. Real Python code would just write `s[::-1]`.",
      ],
      code: `def reverse(s):\n    st = list(s)\n    return "".join(st.pop() for _ in range(len(st)))`,
      time: "O(n)",
      space: "O(n)",
    },
    {
      id: "st-i-11",
      title: "Reverse a stack using recursion (no extra structure)",
      category: "Coding",
      difficulty: "Advanced",
      estMin: 20,
      tags: ["recursion"],
      explanation: [
        "Pop everything to unwind, then on the way back up insert each value at the bottom of the (now smaller) stack. `insert_at_bottom` is itself recursive.",
      ],
      code: `def insert_at_bottom(st, x):\n    if not st: st.append(x); return\n    top = st.pop()\n    insert_at_bottom(st, x)\n    st.append(top)\n\ndef reverse_stack(st):\n    if not st: return\n    top = st.pop()\n    reverse_stack(st)\n    insert_at_bottom(st, top)`,
      time: "O(n²)",
      space: "O(n) call stack",
    },
    {
      id: "st-i-12",
      title: "Sort a stack using recursion",
      category: "Coding",
      difficulty: "Advanced",
      estMin: 25,
      tags: ["recursion"],
      explanation: [
        "Same trick as reverse, but `insert_sorted` pops values greater than x, inserts x, then pushes them back.",
      ],
      code: `def insert_sorted(st, x):\n    if not st or st[-1] <= x: st.append(x); return\n    top = st.pop()\n    insert_sorted(st, x); st.append(top)\ndef sort_stack(st):\n    if not st: return\n    top = st.pop(); sort_stack(st); insert_sorted(st, top)`,
      time: "O(n²)",
      space: "O(n)",
    },
    {
      id: "st-i-13",
      title: "Check if a string is a palindrome using a stack",
      category: "Coding",
      difficulty: "Beginner",
      estMin: 8,
      tags: ["palindrome"],
      explanation: [
        "Push the first half, then compare with the second half. Handle odd length by skipping the middle character.",
      ],
      code: `def is_palindrome(s):\n    n = len(s); st = []\n    for i in range(n // 2): st.append(s[i])\n    start = n // 2 + (n % 2)\n    for i in range(start, n):\n        if st.pop() != s[i]: return False\n    return True`,
      time: "O(n)",
      space: "O(n)",
    },
    {
      id: "st-i-14",
      title: "Valid Parentheses",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 10,
      tags: ["must-do", "parsing"],
      explanation: [
        "Push openers; on each closer, pop and check that it matches. Empty stack at the end means every bracket was closed.",
      ],
      code: `def is_valid(s):\n    pairs = {')':'(', ']':'[', '}':'{'}\n    st = []\n    for c in s:\n        if c in '([{': st.append(c)\n        elif not st or st.pop() != pairs[c]: return False\n    return not st`,
      time: "O(n)",
      space: "O(n)",
      leetcode: {
        title: "20 · Valid Parentheses",
        url: "https://leetcode.com/problems/valid-parentheses/",
        difficulty: "Easy",
      },
    },
    {
      id: "st-i-15",
      title: "Min Stack — push, pop, top, getMin in O(1)",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 20,
      tags: ["must-do", "design"],
      explanation: [
        "Track a parallel stack of running minimums. Every push records `min(x, mn[-1])`; every pop pops both.",
      ],
      code: `class MinStack:\n    def __init__(self): self.st, self.mn = [], []\n    def push(self, x):\n        self.st.append(x); self.mn.append(x if not self.mn else min(x, self.mn[-1]))\n    def pop(self): self.st.pop(); self.mn.pop()\n    def top(self): return self.st[-1]\n    def getMin(self): return self.mn[-1]`,
      time: "O(1)",
      space: "O(n)",
      leetcode: {
        title: "155 · Min Stack",
        url: "https://leetcode.com/problems/min-stack/",
        difficulty: "Medium",
      },
    },
    {
      id: "st-i-16",
      title: "Next Greater Element",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 20,
      tags: ["monotonic-stack"],
      explanation: [
        "Traverse right-to-left maintaining a decreasing stack. For each element, pop while the stack top is not greater — the top after popping is the answer.",
      ],
      code: `def next_greater(a):\n    res, st = [-1] * len(a), []\n    for i in range(len(a) - 1, -1, -1):\n        while st and st[-1] <= a[i]: st.pop()\n        if st: res[i] = st[-1]\n        st.append(a[i])\n    return res`,
      time: "O(n)",
      space: "O(n)",
      leetcode: {
        title: "496 · Next Greater Element I",
        url: "https://leetcode.com/problems/next-greater-element-i/",
        difficulty: "Easy",
      },
      relatedAlgorithm: "monotonic-stack",
    },
    {
      id: "st-i-17",
      title: "Daily Temperatures",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 20,
      tags: ["monotonic-stack"],
      explanation: [
        "Walk left-to-right with a stack of indices of unresolved days. Whenever today's temperature beats the stack top's day, pop and record the day gap.",
      ],
      code: `def daily_temperatures(t):\n    res, st = [0] * len(t), []\n    for i, x in enumerate(t):\n        while st and t[st[-1]] < x:\n            j = st.pop(); res[j] = i - j\n        st.append(i)\n    return res`,
      time: "O(n)",
      space: "O(n)",
      leetcode: {
        title: "739 · Daily Temperatures",
        url: "https://leetcode.com/problems/daily-temperatures/",
        difficulty: "Medium",
      },
      relatedAlgorithm: "monotonic-stack",
    },
    {
      id: "st-i-18",
      title: "Largest Rectangle in Histogram",
      category: "Optimization",
      difficulty: "FAANG",
      estMin: 40,
      tags: ["monotonic-stack", "must-do"],
      explanation: [
        "Sweep bars while maintaining a stack of indices with increasing heights. On a smaller bar, pop and compute the rectangle whose height is the popped bar and whose width extends from just-after the new top to i-1.",
      ],
      time: "O(n)",
      space: "O(n)",
      leetcode: {
        title: "84 · Largest Rectangle in Histogram",
        url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        difficulty: "Hard",
      },
      relatedAlgorithm: "monotonic-stack",
    },
    {
      id: "st-i-19",
      title: "Evaluate Reverse Polish Notation",
      category: "Coding",
      difficulty: "Intermediate",
      estMin: 15,
      tags: ["evaluation"],
      explanation: [
        "One value stack. On a number, push. On an operator, pop the top two operands (order matters!), compute, push the result back. The final stack element is the answer.",
      ],
      code: `def eval_rpn(tokens):\n    st = []\n    for t in tokens:\n        if t in '+-*/':\n            b, a = st.pop(), st.pop()\n            st.append(int(a/b) if t == '/' else eval(f'{a}{t}{b}'))\n        else: st.append(int(t))\n    return st[0]`,
      time: "O(n)",
      space: "O(n)",
      leetcode: {
        title: "150 · Evaluate Reverse Polish Notation",
        url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
        difficulty: "Medium",
      },
    },

    // ── Advanced / Follow-up ─────────────────────────────────────────────
    {
      id: "st-i-20",
      title: "Delete a specific element from a stack (preserve order)",
      category: "Follow-up",
      difficulty: "Intermediate",
      estMin: 15,
      tags: ["recursion"],
      explanation: [
        "Recursively pop until you find the target, discard it, then push the popped values back. Order below the removed element is preserved.",
      ],
      code: `def delete_value(st, x):\n    if not st: return\n    top = st.pop()\n    if top == x: return\n    delete_value(st, x); st.append(top)`,
      time: "O(n)",
      space: "O(n)",
    },
    {
      id: "st-i-21",
      title: "Remove the middle element of a stack",
      category: "Follow-up",
      difficulty: "Intermediate",
      estMin: 15,
      tags: ["recursion"],
      explanation: [
        "Pop `n // 2` elements onto the call stack recursively, drop the middle, then push everything back. Uses the call stack as auxiliary storage.",
      ],
      code: `def remove_middle(st, mid=None):\n    if mid is None: mid = len(st) // 2\n    if not st or mid == 0: st.pop(); return\n    top = st.pop(); remove_middle(st, mid - 1); st.append(top)`,
      time: "O(n)",
      space: "O(n)",
    },
    {
      id: "st-i-22",
      title: "Convert a stack into a queue",
      category: "Follow-up",
      difficulty: "Intermediate",
      estMin: 15,
      tags: ["design"],
      explanation: [
        "Use two stacks. Enqueue pushes onto `in_stack`; dequeue transfers everything into `out_stack` (only when it is empty) so the oldest element ends up on top.",
        "Amortised O(1) per operation.",
      ],
      code: `class Queue:\n    def __init__(self): self.i, self.o = [], []\n    def enqueue(self, x): self.i.append(x)\n    def dequeue(self):\n        if not self.o:\n            while self.i: self.o.append(self.i.pop())\n        return self.o.pop()`,
      time: "amortised O(1)",
      leetcode: {
        title: "232 · Implement Queue using Stacks",
        url: "https://leetcode.com/problems/implement-queue-using-stacks/",
        difficulty: "Easy",
      },
    },
    {
      id: "st-i-23",
      title: "Edge case — pop from an empty stack",
      category: "Edge Case",
      difficulty: "Beginner",
      estMin: 3,
      tags: ["safety"],
      explanation: [
        "Every stack API must decide: raise, return `None`, or return a sentinel? Document the choice. Python's `list.pop()` raises `IndexError` — most user code should catch it or check `is_empty` first.",
      ],
    },
  ],
};
