import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PageShell, PageHeader, Callout } from "@/components/Callout";
import { Section } from "@/components/ListVisualizer";
import { CodeBlock } from "@/components/CodeBlock";
import { PrevNext } from "@/components/PrevNext";
import { Play } from "lucide-react";

export const Route = createFileRoute("/comprehension")({
  head: () => ({
    meta: [
      { title: "List Comprehensions — DSA with Python" },
      { name: "description", content: "Watch values being generated by a comprehension, one by one." },
    ],
  }),
  component: Page,
});

function ComprehensionAnim() {
  const source = [1, 2, 3, 4, 5, 6, 7, 8];
  const [i, setI] = useState(-1);
  const [running, setRunning] = useState(false);

  useEffect(() => {
    if (!running) return;
    const t = setTimeout(() => {
      setI((k) => {
        if (k >= source.length - 1) {
          setRunning(false);
          return k;
        }
        return k + 1;
      });
    }, 500);
    return () => clearTimeout(t);
  }, [running, i]);

  const out: number[] = [];
  for (let k = 0; k <= i && k < source.length; k++) {
    const x = source[k];
    if (x % 2 === 0) out.push(x * x);
  }

  return (
    <div className="card-surface p-4">
      <div className="mb-2 text-xs text-muted-foreground">Source</div>
      <div className="flex gap-2">
        {source.map((v, k) => (
          <div
            key={k}
            className={`grid h-12 w-12 place-items-center rounded-md border font-mono text-lg ${
              k === i ? "border-[color:var(--brand)] bg-[color:var(--brand)]/15" : "border-border bg-card"
            } ${k < i ? "opacity-60" : ""}`}
          >
            {v}
          </div>
        ))}
      </div>
      <div className="mt-4 mb-2 text-xs text-muted-foreground">
        Result: <code>[x*x for x in nums if x % 2 == 0]</code>
      </div>
      <div className="flex min-h-[3rem] gap-2">
        <AnimatePresence>
          {out.map((v, k) => (
            <motion.div
              key={`${k}-${v}`}
              initial={{ opacity: 0, y: -10, scale: 0.8 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              className="grid h-12 w-14 place-items-center rounded-md border border-[color:var(--good)] bg-[color:var(--good)]/15 font-mono text-lg"
            >
              {v}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
      <div className="mt-4 flex gap-2">
        <button
          onClick={() => {
            setI(-1);
            setRunning(true);
          }}
          className="inline-flex items-center gap-1 rounded-md gradient-brand px-3 py-1.5 text-sm text-primary-foreground"
        >
          <Play className="h-4 w-4" /> Run
        </button>
        <button
          onClick={() => {
            setI(-1);
            setRunning(false);
          }}
          className="rounded-md border border-border bg-card px-3 py-1.5 text-sm hover:bg-accent"
        >
          Reset
        </button>
      </div>
    </div>
  );
}

function Page() {
  return (
    <PageShell>
      <PageHeader
        eyebrow="Advanced"
        title="List Comprehension"
        description="A compact way to build a new list from an iterable. Fast, readable, and very Pythonic."
      />

      <Section title="Watch it build">
        <ComprehensionAnim />
      </Section>

      <Section title="Basic form">
        <CodeBlock code={`squares = [x*x for x in range(6)]\n# [0, 1, 4, 9, 16, 25]`} />
      </Section>

      <Section title="With a filter">
        <CodeBlock code={`evens = [x for x in range(20) if x % 2 == 0]\n# [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]`} />
      </Section>

      <Section title="Nested comprehension">
        <CodeBlock
          code={`matrix = [[1,2,3],[4,5,6],[7,8,9]]\nflat = [x for row in matrix for x in row]\n# [1,2,3,4,5,6,7,8,9]`}
        />
      </Section>

      <Section title="Conditional expression">
        <CodeBlock code={`labels = ["even" if x % 2 == 0 else "odd" for x in range(5)]`} />
      </Section>

      <Callout kind="tip">
        A comprehension is almost always faster than an equivalent <code>for</code> + <code>append()</code> loop, and
        the interpreter has dedicated bytecode for it.
      </Callout>

      <PrevNext current="/comprehension" />
    </PageShell>
  );
}
