import type { HTLesson } from "./types";

/** Review & Practice tier — mistakes, FAQ, interview bank, cheat sheets, quiz. */
export const HT_REVISION: HTLesson[] = [
  {
    slug: "common-mistakes",
    title: "Common Mistakes",
    eyebrow: "Revision · 1",
    description: "The full bug list for hashing and hash tables — memorise, then move on.",
    difficulty: "Beginner",
    readMinutes: 4,
    sections: [
      { type: "mistakes", items: [
        "Using a mutable object as a key.",
        "Assuming `hash(x)` is stable across Python processes.",
        "Iterating over a dict while modifying it — RuntimeError.",
        "Defining `__eq__` without `__hash__`.",
        "Choosing a power-of-two modulus with a poor hash — only low bits contribute.",
        "Deleting from open addressing without tombstones.",
        "Reusing a shared mutable default (`d.setdefault(k, [])` is safe; `d = {k: []}` shared is not).",
        "Assuming O(1) worst case — it's only O(1) *average*.",
      ]},
    ],
  },
  {
    slug: "faq",
    title: "Frequently Asked Questions",
    eyebrow: "Revision · 2",
    description: "Answers to the questions learners ask most often.",
    difficulty: "Beginner",
    readMinutes: 6,
    sections: [
      { type: "theory", bullets: [
        "Q · What is hashing? — Mapping a key of arbitrary size to a fixed-size integer.",
        "Q · What is a hash function? — The pure function that performs the mapping.",
        "Q · What makes a good hash function? — Deterministic, uniform, fast, avalanche.",
        "Q · Why are collisions unavoidable? — Pigeonhole principle: infinite keys, finite buckets.",
        "Q · What is the load factor? — α = entries / buckets. Controls speed.",
        "Q · Why is rehashing necessary? — To keep α low as entries accumulate.",
        "Q · Difference between hashing and hash tables? — Hashing is the technique; a hash table is a data structure that uses it.",
        "Q · Difference between dictionary and hash table? — Dictionary is the ADT; hash table is one implementation.",
        "Q · Difference between hash table and array? — Array indexes by position; hash table indexes by key.",
        "Q · Difference between hash table and BST? — Hash is O(1) unordered; BST is O(log n) ordered.",
        "Q · Difference between hash table and set? — Set has no values.",
        "Q · Why are Python dicts so fast? — Compact open addressing, C-level, cache-friendly.",
        "Q · Why O(1) average? — Uniform hash + low load factor ⇒ constant-length probe chains.",
        "Q · Worst-case complexity? — O(n), when every key collides.",
        "Q · What happens when the table becomes full? — It rehashes into a larger table.",
      ]},
    ],
  },
  {
    slug: "interview-questions",
    title: "Interview Questions",
    eyebrow: "Revision · 3",
    description: "The bank you should be able to answer cold.",
    difficulty: "Intermediate",
    readMinutes: 6,
    sections: [
      { type: "interview", items: [
        "Explain O(1) average with O(n) worst-case in one sentence.",
        "Compare separate chaining vs open addressing — memory, cache, deletion.",
        "Compare linear vs quadratic vs double hashing.",
        "Why does CPython use open addressing, not chaining?",
        "Design an LRU cache with O(1) get/put (LeetCode 146).",
        "Two-Sum with a hash map — walk me through the invariant.",
        "Group anagrams — pick a hash key and justify.",
        "Sub-array sum equals K — prefix sums + hash.",
        "Longest consecutive sequence in O(n) — set membership.",
        "How would you build a distributed hash table? (consistent hashing.)",
      ]},
      { type: "callout", kind: "interview", title: "Pattern spotting",
        text: "'Fastest lookup by content' → hash table. 'Count / group / dedupe' → hash map. 'Two elements that sum to X' → hash map complement." },
    ],
  },
  {
    slug: "complexity-cheat-sheet",
    title: "Complexity Cheat Sheet",
    eyebrow: "Revision · 4",
    description: "One table, print it, tape it to your monitor.",
    difficulty: "Beginner",
    readMinutes: 3,
    sections: [
      { type: "complexity", rows: [
        { op: "get / set / del · avg", time: "O(1)", space: "O(n)" },
        { op: "get / set / del · worst", time: "O(n)" },
        { op: "iteration", time: "O(n)" },
        { op: "resize / rehash", time: "O(n)", note: "amortised O(1) per insert" },
        { op: "membership · in", time: "O(1) avg" },
        { op: "copy", time: "O(n)", space: "O(n)" },
      ]},
    ],
  },
  {
    slug: "hashing-cheat-sheet",
    title: "Hashing Cheat Sheet",
    eyebrow: "Revision · 5",
    description: "Every hashing technique in one page.",
    difficulty: "Beginner",
    readMinutes: 3,
    sections: [
      { type: "theory", bullets: [
        "Division — `h(k) = k mod m`. m = prime.",
        "Multiplication — `⌊m · frac(k·A)⌋`, A ≈ 0.618.",
        "Mid-square — square k, take middle bits.",
        "Folding — chunk k, sum chunks, mod m.",
        "Digit extraction — keep varying digits.",
        "Universal — pick h at runtime from a family.",
        "Polynomial — Σ ord(c) · p^i (mod m).",
        "Rolling — update polynomial hash in O(1) per slide.",
        "Cryptographic — SHA-256, BLAKE3. Not for `dict`.",
      ]},
    ],
  },
  {
    slug: "collision-comparison",
    title: "Collision Resolution Comparison",
    eyebrow: "Revision · 6",
    description: "Pick the right scheme in five seconds.",
    difficulty: "Intermediate",
    readMinutes: 3,
    sections: [
      { type: "complexity", rows: [
        { op: "chaining", time: "O(1 + α)", note: "robust, less cache-friendly, unbounded α" },
        { op: "linear probing", time: "O(1) at α<0.7", note: "cache-friendly, primary clustering" },
        { op: "quadratic probing", time: "O(1) at α<0.5", note: "breaks clusters, may miss slots" },
        { op: "double hashing", time: "O(1) at α<0.9", note: "near-uniform, CPython's choice" },
        { op: "robin hood", time: "O(1)", note: "flattens variance, complex insert" },
        { op: "cuckoo", time: "O(1) worst-case get", note: "two tables, two hashes" },
      ]},
    ],
  },
  {
    slug: "practice",
    title: "Practice Problems",
    eyebrow: "Revision · 7",
    description: "Every problem worth doing before the interview loop.",
    difficulty: "Intermediate",
    readMinutes: 4,
    sections: [
      { type: "practice", groups: [
        { level: "Beginner", items: [
          { title: "LC 1 · Two Sum", url: "https://leetcode.com/problems/two-sum/", difficulty: "Easy" },
          { title: "LC 217 · Contains Duplicate", url: "https://leetcode.com/problems/contains-duplicate/", difficulty: "Easy" },
          { title: "LC 242 · Valid Anagram", url: "https://leetcode.com/problems/valid-anagram/", difficulty: "Easy" },
          { title: "LC 383 · Ransom Note", url: "https://leetcode.com/problems/ransom-note/", difficulty: "Easy" },
        ]},
        { level: "Intermediate", items: [
          { title: "LC 3 · Longest Substring Without Repeat", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", difficulty: "Medium" },
          { title: "LC 49 · Group Anagrams", url: "https://leetcode.com/problems/group-anagrams/", difficulty: "Medium" },
          { title: "LC 560 · Subarray Sum Equals K", url: "https://leetcode.com/problems/subarray-sum-equals-k/", difficulty: "Medium" },
          { title: "LC 128 · Longest Consecutive Sequence", url: "https://leetcode.com/problems/longest-consecutive-sequence/", difficulty: "Medium" },
          { title: "LC 380 · Insert Delete GetRandom O(1)", url: "https://leetcode.com/problems/insert-delete-getrandom-o1/", difficulty: "Medium" },
        ]},
        { level: "Advanced", items: [
          { title: "LC 146 · LRU Cache", url: "https://leetcode.com/problems/lru-cache/", difficulty: "Medium" },
          { title: "LC 460 · LFU Cache", url: "https://leetcode.com/problems/lfu-cache/", difficulty: "Hard" },
          { title: "LC 76 · Minimum Window Substring", url: "https://leetcode.com/problems/minimum-window-substring/", difficulty: "Hard" },
          { title: "LC 41 · First Missing Positive", url: "https://leetcode.com/problems/first-missing-positive/", difficulty: "Hard" },
        ]},
      ]},
    ],
  },
  {
    slug: "leetcode-roadmap",
    title: "LeetCode Roadmap",
    eyebrow: "Revision · 8",
    description: "A 15-problem path from cold-start to interview-ready.",
    difficulty: "Intermediate",
    readMinutes: 3,
    sections: [
      { type: "theory", bullets: [
        "Warm-up: 1 · Two Sum → 217 · Contains Duplicate → 242 · Valid Anagram.",
        "Bucket keys: 49 · Group Anagrams → 438 · Find All Anagrams.",
        "Prefix sums + hash: 560 · Subarray Sum → 974 · Divisible-by-K subarrays.",
        "Sliding window + hash: 3 · Longest Substring → 76 · Min Window Substring.",
        "Design: 146 · LRU → 460 · LFU → 380 · O(1) random.",
        "Tricky index-as-key: 41 · First Missing Positive → 128 · Longest Consecutive.",
      ]},
    ],
  },
  {
    slug: "hackerrank-roadmap",
    title: "HackerRank Roadmap",
    eyebrow: "Revision · 9",
    description: "The equivalent path on HackerRank's dictionaries & hashmaps track.",
    difficulty: "Intermediate",
    readMinutes: 3,
    sections: [
      { type: "theory", bullets: [
        "Ransom Note.",
        "Two Strings.",
        "Sherlock and Anagrams.",
        "Count Triplets.",
        "Frequency Queries.",
      ]},
      { type: "references", items: [
        { label: "HackerRank · Dictionaries & Hashmaps", url: "https://www.hackerrank.com/domains/data-structures/hash-tables" },
      ]},
    ],
  },
  {
    slug: "references",
    title: "References",
    eyebrow: "Revision · 10",
    description: "Everything worth bookmarking.",
    difficulty: "Beginner",
    readMinutes: 2,
    sections: [
      { type: "references", items: [
        { label: "Python docs · dict", url: "https://docs.python.org/3/library/stdtypes.html#dict" },
        { label: "Python docs · set", url: "https://docs.python.org/3/library/stdtypes.html#set" },
        { label: "CPython dictobject.c", url: "https://github.com/python/cpython/blob/main/Objects/dictobject.c" },
        { label: "PEP 456 · Secure hashing", url: "https://peps.python.org/pep-0456/" },
        { label: "PEP 468 · Compact ordered dict", url: "https://peps.python.org/pep-0468/" },
        { label: "Raymond Hettinger · Modern Dictionaries", url: "https://www.youtube.com/watch?v=npw4s1QTmPg" },
        { label: "CLRS · Chapter 11", url: "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/" },
      ]},
    ],
  },
  {
    slug: "final-quiz",
    title: "Final Quiz",
    eyebrow: "Revision · 11",
    description: "Ten questions across foundations, hashing, and tables.",
    difficulty: "Intermediate",
    readMinutes: 6,
    sections: [
      { type: "quiz", items: [
        { q: "The average time complexity of dict get() in Python is:",
          choices: ["O(log n)", "O(1)", "O(n)", "O(n log n)"], answer: 1 },
        { q: "Which of these is unhashable?",
          choices: ["tuple of ints", "frozenset", "list", "str"], answer: 2 },
        { q: "CPython's dict uses which collision strategy?",
          choices: ["Separate chaining", "Open addressing with perturbed probing", "Cuckoo hashing", "Robin Hood hashing"], answer: 1 },
        { q: "Load factor is defined as:",
          choices: ["entries × buckets", "entries + buckets", "entries / buckets", "buckets / entries"], answer: 2 },
        { q: "The purpose of a tombstone slot is to:",
          choices: ["Save memory", "Preserve probe sequences after deletion", "Prevent duplicate keys", "Speed up rehash"], answer: 1 },
        { q: "Amortised insert cost when doubling on resize:",
          choices: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0 },
        { q: "Which hashing technique guarantees O(1) worst-case lookup on a static key set?",
          choices: ["Universal", "Perfect", "Polynomial", "Rolling"], answer: 1 },
        { q: "Which technique is best for text search over sliding windows?",
          choices: ["Universal", "Perfect", "Polynomial", "Rolling"], answer: 3 },
        { q: "Python dicts preserve insertion order since:",
          choices: ["3.5", "3.6 (impl), 3.7 (spec)", "3.8", "3.10"], answer: 1 },
        { q: "Best structure for O(1) membership plus O(log n) ordered iteration?",
          choices: ["dict", "set", "sorted list", "balanced BST"], answer: 3 },
      ]},
    ],
  },
  {
    slug: "next-topic",
    title: "Next Topic",
    eyebrow: "Revision · 12",
    description: "Where to go from here.",
    difficulty: "Beginner",
    readMinutes: 2,
    sections: [
      { type: "theory", text: "You've mastered a linear key/value structure. Non-linear structures like Trees and Graphs come next — many of which use hash tables internally (e.g. adjacency maps for graphs, memoisation tables for DP)." },
      { type: "callout", kind: "tip", title: "Continue learning",
        text: "Trees introduce hierarchy and ordered iteration. Graphs bring the algorithms that combine hash tables with BFS/DFS." },
    ],
  },
];
