import { GraphPreset } from "./types";

export const PRESETS: GraphPreset[] = [
  {
    id: "default",
    name: "Default Weighted Graph",
    description: "Standard connected graph with weighted edges. Good for pathfinding and minimum spanning trees.",
    nodes: [
      { id: 0, label: "A", x: 90, y: 80 },
      { id: 1, label: "B", x: 260, y: 60 },
      { id: 2, label: "C", x: 430, y: 100 },
      { id: 3, label: "D", x: 160, y: 220 },
      { id: 4, label: "E", x: 340, y: 220 },
      { id: 5, label: "F", x: 90, y: 360 },
      { id: 6, label: "G", x: 260, y: 380 },
      { id: 7, label: "H", x: 430, y: 340 },
    ],
    edges: [
      { u: 0, v: 1, w: 4 },
      { u: 0, v: 3, w: 2 },
      { u: 1, v: 2, w: 3 },
      { u: 1, v: 4, w: 5 },
      { u: 2, v: 4, w: 1 },
      { u: 2, v: 7, w: 6 },
      { u: 3, v: 4, w: 3 },
      { u: 3, v: 5, w: 4 },
      { u: 3, v: 6, w: 6 },
      { u: 4, v: 6, w: 2 },
      { u: 4, v: 7, w: 4 },
      { u: 5, v: 6, w: 3 },
      { u: 6, v: 7, w: 5 },
    ],
    directed: false,
    weighted: true,
    compatibleAlgos: ["bfs", "dfs", "dijkstra", "bellman-ford", "floyd-warshall", "prim", "kruskal", "scc", "union-find"],
  },
  {
    id: "dag",
    name: "Directed Acyclic Graph (DAG)",
    description: "A directed graph with no cycles. Perfect for demonstrating Topological Sort.",
    nodes: [
      { id: 0, label: "A", x: 100, y: 80 },
      { id: 1, label: "B", x: 260, y: 80 },
      { id: 2, label: "C", x: 420, y: 80 },
      { id: 3, label: "D", x: 100, y: 240 },
      { id: 4, label: "E", x: 260, y: 240 },
      { id: 5, label: "F", x: 420, y: 240 },
    ],
    edges: [
      { u: 0, v: 1, w: 1 },
      { u: 0, v: 3, w: 1 },
      { u: 1, v: 2, w: 1 },
      { u: 1, v: 4, w: 1 },
      { u: 3, v: 4, w: 1 },
      { u: 4, v: 2, w: 1 },
      { u: 4, v: 5, w: 1 },
      { u: 2, v: 5, w: 1 },
    ],
    directed: true,
    weighted: false,
    compatibleAlgos: ["bfs", "dfs", "topo-sort"],
  },
  {
    id: "neg-weights",
    name: "Negative Edge Graph",
    description: "Contains negative-weight edges but NO negative cycles. Dijkstra fails here, but Bellman-Ford succeeds.",
    nodes: [
      { id: 0, label: "A", x: 90, y: 200 },
      { id: 1, label: "B", x: 230, y: 100 },
      { id: 2, label: "C", x: 230, y: 300 },
      { id: 3, label: "D", x: 380, y: 200 },
    ],
    edges: [
      { u: 0, v: 1, w: 4 },
      { u: 0, v: 2, w: 3 },
      { u: 1, v: 2, w: -2 },
      { u: 1, v: 3, w: 2 },
      { u: 2, v: 3, w: 1 },
    ],
    directed: true,
    weighted: true,
    compatibleAlgos: ["bellman-ford", "floyd-warshall", "dijkstra"],
  },
  {
    id: "neg-cycle",
    name: "Negative Cycle Graph",
    description: "Contains a negative weight cycle (B -> C -> D -> B = -1). Bellman-Ford should detect and report it.",
    nodes: [
      { id: 0, label: "A", x: 90, y: 200 },
      { id: 1, label: "B", x: 230, y: 100 },
      { id: 2, label: "C", x: 370, y: 200 },
      { id: 3, label: "D", x: 230, y: 300 },
    ],
    edges: [
      { u: 0, v: 1, w: 2 },
      { u: 1, v: 2, w: 3 },
      { u: 2, v: 3, w: -7 },
      { u: 3, v: 1, w: 3 },
    ],
    directed: true,
    weighted: true,
    compatibleAlgos: ["bellman-ford", "floyd-warshall"],
  },
  {
    id: "scc-graph",
    name: "Strongly Connected Components",
    description: "Directed graph with multiple cycles, ideal for Kosaraju's SCC extraction.",
    nodes: [
      { id: 0, label: "A", x: 100, y: 100 },
      { id: 1, label: "B", x: 260, y: 100 },
      { id: 2, label: "C", x: 420, y: 100 },
      { id: 3, label: "D", x: 100, y: 280 },
      { id: 4, label: "E", x: 260, y: 280 },
    ],
    edges: [
      { u: 0, v: 1, w: 1 },
      { u: 1, v: 3, w: 1 },
      { u: 3, v: 0, w: 1 },
      { u: 1, v: 2, w: 1 },
      { u: 2, v: 4, w: 1 },
      { u: 4, v: 2, w: 1 },
    ],
    directed: true,
    weighted: false,
    compatibleAlgos: ["scc", "bfs", "dfs"],
  },
  {
    id: "sparse-union",
    name: "Sparse Forest (Union-Find)",
    description: "Several isolated nodes. Perfect for demonstrating DSU merges and path compressions.",
    nodes: [
      { id: 0, label: "A", x: 90, y: 100 },
      { id: 1, label: "B", x: 220, y: 100 },
      { id: 2, label: "C", x: 350, y: 100 },
      { id: 3, label: "D", x: 480, y: 100 },
      { id: 4, label: "E", x: 90, y: 260 },
      { id: 5, label: "F", x: 220, y: 260 },
      { id: 6, label: "G", x: 350, y: 260 },
      { id: 7, label: "H", x: 480, y: 260 },
    ],
    edges: [],
    directed: false,
    weighted: false,
    compatibleAlgos: ["union-find", "kruskal"],
  },
];
