import type { ModuleBank } from "../types";

export const arraysBank: ModuleBank = {
  moduleSlug: "arrays",
  moduleTitle: "Arrays & Python Lists",
  edgeCases: [
    {
      case: "Empty array",
      why: "Most algorithms need a guard: len(arr) == 0 to avoid IndexError.",
      example: "arr = []",
    },
    {
      case: "Single element",
      why: "Two-pointer and window logic often collapses; return early.",
      example: "arr = [5]",
    },
    {
      case: "All duplicates",
      why: "Sets/frequency approaches degenerate; watch for O(n²) with naive scan.",
      example: "arr = [3,3,3,3]",
    },
    {
      case: "Already sorted",
      why: "Best case for many algorithms — verify complexity stays bounded.",
      example: "arr = [1,2,3,4,5]",
    },
    {
      case: "Reverse sorted",
      why: "Worst case for many sorts, particularly quicksort with naive pivot.",
      example: "arr = [9,7,5,3,1]",
    },
    {
      case: "Negative numbers",
      why: "Prefix sums, Kadane's, and min/max init to 0 fail.",
      example: "arr = [-3,-1,-4]",
    },
    {
      case: "Very large input",
      why: "Watch O(n²) — 10^5 items = 10^10 ops = timeout.",
      example: "n = 10**6",
    },
    {
      case: "Off-by-one at boundaries",
      why: "Loops using range(len(arr)-1) are the #1 bug source.",
      example: "for i in range(n-1)",
    },
  ],
  revisionSheet: {
    formulas: [
      "mid = left + (right - left) // 2",
      "prefix[i] = prefix[i-1] + arr[i]",
      "windowSum += arr[right] - arr[left]",
    ],
    timeComplexity: [
      { op: "Access arr[i]", time: "O(1)" },
      { op: "Append", time: "O(1) amortized" },
      { op: "Insert at index", time: "O(n)" },
      { op: "Delete by value", time: "O(n)" },
      { op: "Search (linear)", time: "O(n)" },
      { op: "Search (binary, sorted)", time: "O(log n)" },
      { op: "Sort", time: "O(n log n)" },
    ],
    spaceComplexity: [
      { op: "Storage", space: "O(n)" },
      { op: "In-place reverse", space: "O(1)" },
      { op: "Slice copy", space: "O(k)" },
    ],
    commonMistakes: [
      "Modifying a list while iterating over it",
      "Using == on lists but expecting reference equality",
      "Forgetting arr[:] creates a shallow copy of the outer list only",
      "Off-by-one when computing window/subarray boundaries",
      "Assuming .sort() returns the sorted list (it returns None)",
    ],
    memoryTricks: [
      "Two pointers when input is sorted",
      "Sliding window when 'contiguous subarray' appears",
      "Prefix sum when 'range sum' or 'sum equals k' appears",
      "Hash map when 'find pair / complement' appears",
    ],
    mustSolve: ["q-arr-two-sum", "q-arr-max-subarray", "q-arr-product-except", "q-arr-rotate"],
  },
  questions: [
    {
      id: "q-arr-what-is-array",
      moduleSlug: "arrays",
      title: "What is an array? How is a Python list different from a C array?",
      category: "theory",
      difficulty: "Beginner",
      topic: "Fundamentals",
      description:
        "Explain the abstract array data structure, then contrast a fixed-size, homogeneous C array with Python's dynamic, heterogeneous list.",
      hints: ["Think about memory layout, size, and element types."],
      pythonSolution:
        "# CPython list is a dynamic array of PyObject* pointers.\n# It over-allocates on append so amortized append is O(1).\narr = [1, 'two', 3.0, [4]]  # heterogeneous — legal in Python\nprint(type(arr), len(arr))",
      visualizationType: "array",
      timeComplexity: "—",
      spaceComplexity: "O(n)",
      estimatedMinutes: 5,
      pattern: "Fundamentals",
      relatedDataStructure: "Array",
      tags: ["theory", "memory", "python-internals"],
      interviewFrequency: "High",
    },
    {
      id: "q-arr-reverse",
      moduleSlug: "arrays",
      title: "Reverse an array in place",
      category: "implementation",
      difficulty: "Beginner",
      topic: "Traversal",
      description: "Reverse the elements of an array without using extra space.",
      hints: ["Two pointers from both ends.", "Swap and move inward until they meet."],
      approaches: [
        {
          name: "Brute",
          code: "return arr[::-1]  # creates a new list (O(n) space)",
          time: "O(n)",
          space: "O(n)",
        },
        {
          name: "Optimal",
          code: "l, r = 0, len(arr) - 1\nwhile l < r:\n    arr[l], arr[r] = arr[r], arr[l]\n    l += 1\n    r -= 1",
          time: "O(n)",
          space: "O(1)",
          note: "In-place two-pointer swap.",
        },
      ],
      visualizationType: "array",
      timeComplexity: "O(n)",
      spaceComplexity: "O(1)",
      estimatedMinutes: 8,
      pattern: "Two Pointers",
      relatedDataStructure: "Array",
      leetcodeLinks: [
        {
          title: "Reverse String",
          url: "https://leetcode.com/problems/reverse-string/",
          difficulty: "Easy",
        },
      ],
      tags: ["two-pointers", "in-place"],
      interviewFrequency: "High",
    },
    {
      id: "q-arr-two-sum",
      moduleSlug: "arrays",
      title: "Two Sum",
      category: "intermediate",
      difficulty: "Interview",
      topic: "Hashing",
      description:
        "Given nums and target, return indices of the two numbers that add up to target.",
      hints: ["Brute force is O(n²).", "What if you stored complements in a hash map as you scan?"],
      approaches: [
        {
          name: "Brute",
          code: "for i in range(len(nums)):\n    for j in range(i+1, len(nums)):\n        if nums[i] + nums[j] == target:\n            return [i, j]",
          time: "O(n²)",
          space: "O(1)",
        },
        {
          name: "Optimal",
          code: "seen = {}\nfor i, x in enumerate(nums):\n    if target - x in seen:\n        return [seen[target - x], i]\n    seen[x] = i",
          time: "O(n)",
          space: "O(n)",
          note: "One pass with a hash map storing value → index.",
        },
      ],
      dryRun:
        "nums=[2,7,11,15], target=9\ni=0 x=2 seen={}  need 7  → store {2:0}\ni=1 x=7 need 2 → found! return [0,1]",
      visualizationType: "array",
      timeComplexity: "O(n)",
      spaceComplexity: "O(n)",
      estimatedMinutes: 15,
      pattern: "Hash Map",
      relatedAlgorithm: "hash-map",
      companies: ["Amazon", "Google", "Microsoft", "Meta", "Apple"],
      interviewFrequency: "Very High",
      leetcodeLinks: [
        { title: "1. Two Sum", url: "https://leetcode.com/problems/two-sum/", difficulty: "Easy" },
      ],
      relatedQuestions: ["q-arr-product-except", "q-arr-max-subarray"],
      tags: ["hash-map", "array", "must-do"],
    },
    {
      id: "q-arr-max-subarray",
      moduleSlug: "arrays",
      title: "Maximum Subarray (Kadane's Algorithm)",
      category: "intermediate",
      difficulty: "Interview",
      topic: "DP",
      description: "Find the contiguous subarray with the largest sum.",
      hints: ["Track the best sum ending here.", "Reset when it drops below zero."],
      approaches: [
        {
          name: "Brute",
          code: "best = float('-inf')\nfor i in range(len(nums)):\n    s = 0\n    for j in range(i, len(nums)):\n        s += nums[j]\n        best = max(best, s)\nreturn best",
          time: "O(n²)",
          space: "O(1)",
        },
        {
          name: "Optimal",
          code: "best = cur = nums[0]\nfor x in nums[1:]:\n    cur = max(x, cur + x)\n    best = max(best, cur)\nreturn best",
          time: "O(n)",
          space: "O(1)",
          note: "Kadane's — extend or restart at each index.",
        },
      ],
      visualizationType: "array",
      timeComplexity: "O(n)",
      spaceComplexity: "O(1)",
      estimatedMinutes: 20,
      pattern: "Kadane",
      relatedAlgorithm: "kadane",
      companies: ["Amazon", "Microsoft", "Bloomberg"],
      interviewFrequency: "Very High",
      leetcodeLinks: [
        {
          title: "53. Maximum Subarray",
          url: "https://leetcode.com/problems/maximum-subarray/",
          difficulty: "Medium",
        },
      ],
      tags: ["dp", "kadane"],
    },
    {
      id: "q-arr-product-except",
      moduleSlug: "arrays",
      title: "Product of Array Except Self",
      category: "advanced",
      difficulty: "Interview",
      topic: "Prefix",
      description:
        "Return an array such that answer[i] equals the product of all elements except nums[i]. No division allowed.",
      hints: [
        "Prefix products from the left.",
        "Suffix products from the right.",
        "Combine in O(1) extra space.",
      ],
      approaches: [
        {
          name: "Better",
          code: "n = len(nums)\nleft = [1]*n; right = [1]*n\nfor i in range(1, n): left[i] = left[i-1]*nums[i-1]\nfor i in range(n-2, -1, -1): right[i] = right[i+1]*nums[i+1]\nreturn [left[i]*right[i] for i in range(n)]",
          time: "O(n)",
          space: "O(n)",
        },
        {
          name: "Optimal",
          code: "n = len(nums)\nout = [1]*n\nleft = 1\nfor i in range(n):\n    out[i] = left\n    left *= nums[i]\nright = 1\nfor i in range(n-1, -1, -1):\n    out[i] *= right\n    right *= nums[i]\nreturn out",
          time: "O(n)",
          space: "O(1)",
          note: "Output array does not count toward space complexity.",
        },
      ],
      visualizationType: "array",
      estimatedMinutes: 25,
      pattern: "Prefix Sum",
      interviewFrequency: "Very High",
      companies: ["Amazon", "Meta", "Google"],
      leetcodeLinks: [
        {
          title: "238. Product of Array Except Self",
          url: "https://leetcode.com/problems/product-of-array-except-self/",
          difficulty: "Medium",
        },
      ],
      tags: ["prefix", "must-do"],
    },
    {
      id: "q-arr-rotate",
      moduleSlug: "arrays",
      title: "Rotate Array by K",
      category: "intermediate",
      difficulty: "Intermediate",
      topic: "Manipulation",
      description: "Rotate the array to the right by k steps in place.",
      hints: ["k %= n first.", "Reverse whole, reverse first k, reverse rest."],
      approaches: [
        {
          name: "Optimal",
          code: "def rotate(nums, k):\n    n = len(nums); k %= n\n    def rev(l, r):\n        while l < r: nums[l], nums[r] = nums[r], nums[l]; l += 1; r -= 1\n    rev(0, n-1); rev(0, k-1); rev(k, n-1)",
          time: "O(n)",
          space: "O(1)",
        },
      ],
      estimatedMinutes: 15,
      pattern: "Reversal",
      leetcodeLinks: [
        {
          title: "189. Rotate Array",
          url: "https://leetcode.com/problems/rotate-array/",
          difficulty: "Medium",
        },
      ],
      tags: ["in-place", "reversal"],
      interviewFrequency: "High",
    },
    {
      id: "q-arr-edge-empty",
      moduleSlug: "arrays",
      title: "Handle empty & single-element inputs safely",
      category: "edge-case",
      difficulty: "Beginner",
      topic: "Edge Cases",
      description:
        "Design your function so it returns a sensible default for `[]` and `[x]` before your main logic runs.",
      pythonSolution:
        "def max_sum(arr):\n    if not arr: return 0\n    if len(arr) == 1: return arr[0]\n    # ... main logic\n    return sum(arr)",
      estimatedMinutes: 5,
      tags: ["edge", "defensive"],
    },
  ],
};
