import type { ModuleBank } from "../types";

// Lightweight starter banks for modules that don't yet have a deep-dive file.
// The same schema — future contributors can graduate one to its own file.

function scaffold(slug: string, title: string, extras: Partial<ModuleBank> = {}): ModuleBank {
  return {
    moduleSlug: slug,
    moduleTitle: title,
    edgeCases: extras.edgeCases ?? [
      { case: "Empty input", why: "Guard against len == 0 before your main logic." },
      { case: "Single element", why: "Return early — algorithms usually collapse here." },
      { case: "Very large input", why: "Check that your complexity fits within limits." },
    ],
    revisionSheet: extras.revisionSheet ?? {
      timeComplexity: [{ op: "See module page", time: "—" }],
      commonMistakes: ["Skipping edge-case checks", "Confusing worst vs average complexity"],
      memoryTricks: ["Draw the structure before coding", "Trace one small example on paper"],
      mustSolve: [],
    },
    questions: extras.questions ?? [
      {
        id: `q-${slug}-theory`,
        moduleSlug: slug,
        title: `Explain the core idea behind ${title.toLowerCase()}`,
        category: "theory",
        difficulty: "Beginner",
        topic: "Fundamentals",
        description: `Describe the structure/algorithm behind ${title}, when to reach for it, and its main trade-offs.`,
        estimatedMinutes: 5,
        tags: ["theory"],
      },
      {
        id: `q-${slug}-impl`,
        moduleSlug: slug,
        title: `Implement a minimal ${title} in Python`,
        category: "implementation",
        difficulty: "Beginner",
        topic: "Implementation",
        description: `Write a from-scratch implementation covering the essential operations of ${title}.`,
        estimatedMinutes: 15,
        tags: ["implementation"],
      },
      {
        id: `q-${slug}-interview`,
        moduleSlug: slug,
        title: `Classic interview question on ${title}`,
        category: "interview",
        difficulty: "Interview",
        topic: "Interview",
        description: `Walk through the most commonly asked interview problem for ${title}.`,
        estimatedMinutes: 20,
        tags: ["interview"],
      },
    ],
  };
}

export const genericBanks: Record<string, ModuleBank> = {
  "python-basics": scaffold("python-basics", "Python Basics"),
  strings: scaffold("strings", "Strings", {
    questions: [
      {
        id: "q-str-anagram",
        moduleSlug: "strings",
        title: "Valid Anagram",
        category: "intermediate",
        difficulty: "Beginner",
        topic: "Hashing",
        description: "Check whether two strings are anagrams.",
        approaches: [
          { name: "Brute", code: "return sorted(s) == sorted(t)", time: "O(n log n)", space: "O(n)" },
          {
            name: "Optimal",
            code: "from collections import Counter\nreturn Counter(s) == Counter(t)",
            time: "O(n)",
            space: "O(1)",
            note: "Counter is O(n); comparison is O(unique chars).",
          },
        ],
        leetcodeLinks: [{ title: "242. Valid Anagram", url: "https://leetcode.com/problems/valid-anagram/", difficulty: "Easy" }],
        interviewFrequency: "Very High",
        estimatedMinutes: 10,
        tags: ["must-do"],
      },
      {
        id: "q-str-palindrome",
        moduleSlug: "strings",
        title: "Valid Palindrome",
        category: "implementation",
        difficulty: "Beginner",
        topic: "Two Pointers",
        description: "Ignoring non-alphanumeric characters, check if a string reads the same forward and backward.",
        approaches: [
          {
            name: "Optimal",
            code: "l, r = 0, len(s)-1\nwhile l < r:\n    while l < r and not s[l].isalnum(): l += 1\n    while l < r and not s[r].isalnum(): r -= 1\n    if s[l].lower() != s[r].lower(): return False\n    l += 1; r -= 1\nreturn True",
            time: "O(n)",
            space: "O(1)",
          },
        ],
        leetcodeLinks: [{ title: "125. Valid Palindrome", url: "https://leetcode.com/problems/valid-palindrome/", difficulty: "Easy" }],
        interviewFrequency: "High",
        estimatedMinutes: 15,
        tags: ["two-pointers"],
      },
      {
        id: "q-str-longest-substring",
        moduleSlug: "strings",
        title: "Longest Substring Without Repeating Characters",
        category: "advanced",
        difficulty: "Interview",
        topic: "Sliding Window",
        description: "Find the length of the longest substring with all unique characters.",
        approaches: [
          {
            name: "Optimal",
            code: "seen = {}; l = best = 0\nfor r, c in enumerate(s):\n    if c in seen and seen[c] >= l:\n        l = seen[c] + 1\n    seen[c] = r\n    best = max(best, r - l + 1)\nreturn best",
            time: "O(n)",
            space: "O(min(n, |Σ|))",
          },
        ],
        leetcodeLinks: [{ title: "3. Longest Substring Without Repeating Characters", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", difficulty: "Medium" }],
        interviewFrequency: "Very High",
        pattern: "Sliding Window",
        relatedAlgorithm: "sliding-window",
        estimatedMinutes: 25,
        tags: ["must-do", "sliding-window"],
      },
    ],
  }),
  recursion: scaffold("recursion", "Recursion"),
  bst: scaffold("bst", "Binary Search Trees"),
  avl: scaffold("avl", "AVL Trees"),
  heaps: scaffold("heaps", "Heaps", {
    questions: [
      {
        id: "q-heap-kth-largest",
        moduleSlug: "heaps",
        title: "Kth Largest Element in an Array",
        category: "intermediate",
        difficulty: "Interview",
        topic: "Heap",
        description: "Return the kth largest element using a min-heap of size k.",
        approaches: [
          {
            name: "Optimal",
            code: "import heapq\nh = nums[:k]; heapq.heapify(h)\nfor x in nums[k:]:\n    if x > h[0]: heapq.heapreplace(h, x)\nreturn h[0]",
            time: "O(n log k)",
            space: "O(k)",
          },
        ],
        leetcodeLinks: [{ title: "215. Kth Largest Element", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "Medium" }],
        interviewFrequency: "Very High",
        estimatedMinutes: 15,
        pattern: "Heap",
        tags: ["must-do"],
      },
      {
        id: "q-heap-topk",
        moduleSlug: "heaps",
        title: "Top K Frequent Elements",
        category: "advanced",
        difficulty: "Interview",
        topic: "Heap",
        description: "Return the k most frequent elements.",
        approaches: [
          {
            name: "Optimal",
            code: "from collections import Counter\nimport heapq\nreturn [x for x, _ in Counter(nums).most_common(k)]",
            time: "O(n log k)",
            space: "O(n)",
          },
        ],
        leetcodeLinks: [{ title: "347. Top K Frequent", url: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "Medium" }],
        interviewFrequency: "Very High",
        estimatedMinutes: 15,
        tags: ["must-do"],
      },
    ],
  }),
  "priority-queues": scaffold("priority-queues", "Priority Queues"),
  tries: scaffold("tries", "Tries"),
  "graph-algorithms": scaffold("graph-algorithms", "Graph Algorithms"),
  "advanced-graphs": scaffold("advanced-graphs", "Advanced Graph Algorithms"),
  dp: scaffold("dp", "Dynamic Programming", {
    questions: [
      {
        id: "q-dp-fib",
        moduleSlug: "dp",
        title: "Fibonacci — recursion, memo, tabulation, O(1)",
        category: "implementation",
        difficulty: "Beginner",
        topic: "Intro",
        description: "Progress from naive recursion to O(n) memo to O(1) space.",
        approaches: [
          { name: "Brute", code: "def f(n): return n if n<2 else f(n-1)+f(n-2)", time: "O(2^n)", space: "O(n)" },
          {
            name: "Better",
            code: "from functools import lru_cache\n@lru_cache(None)\ndef f(n): return n if n<2 else f(n-1)+f(n-2)",
            time: "O(n)",
            space: "O(n)",
          },
          {
            name: "Optimal",
            code: "def f(n):\n    a, b = 0, 1\n    for _ in range(n): a, b = b, a+b\n    return a",
            time: "O(n)",
            space: "O(1)",
          },
        ],
        estimatedMinutes: 15,
        tags: ["intro"],
      },
      {
        id: "q-dp-climb",
        moduleSlug: "dp",
        title: "Climbing Stairs",
        category: "intermediate",
        difficulty: "Beginner",
        topic: "1D DP",
        description: "How many distinct ways to climb n stairs when you can take 1 or 2 steps?",
        approaches: [
          {
            name: "Optimal",
            code: "a, b = 1, 1\nfor _ in range(n): a, b = b, a+b\nreturn a",
            time: "O(n)",
            space: "O(1)",
          },
        ],
        leetcodeLinks: [{ title: "70. Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs/", difficulty: "Easy" }],
        interviewFrequency: "Very High",
        estimatedMinutes: 10,
        tags: ["must-do"],
      },
    ],
  }),
  cp: scaffold("cp", "Competitive Programming Patterns"),
  interview: scaffold("interview", "Interview Preparation"),
};
