import type { ModuleBank } from "../types";

export const linkedListsBank: ModuleBank = {
  moduleSlug: "linked-lists",
  moduleTitle: "Linked Lists",
  edgeCases: [
    { case: "Empty list (head is None)", why: "Every algorithm must guard `if not head:` first.", example: "head = None" },
    { case: "Single node", why: "next is None — reversal/cycle logic can misfire.", example: "1 -> None" },
    { case: "Two nodes", why: "Common off-by-one in slow/fast pointers.", example: "1 -> 2 -> None" },
    { case: "Cycle present", why: "Naive traversal loops forever; use Floyd's slow/fast.", example: "3 -> 2 -> 0 -> -4 -> (back to 2)" },
    { case: "Duplicate values", why: "Value-based delete removes only the first match unless you loop." },
    { case: "Deleting the head", why: "Special case — return `head.next`." },
    { case: "Deleting the tail", why: "Requires the previous node; keep `prev` while walking." },
  ],
  revisionSheet: {
    formulas: ["reverse: prev, cur = None, head; cur.next, prev, cur = prev, cur, cur.next"],
    timeComplexity: [
      { op: "Access i-th", time: "O(n)" },
      { op: "Insert at head", time: "O(1)" },
      { op: "Insert at tail (with tail)", time: "O(1)" },
      { op: "Delete by value", time: "O(n)" },
      { op: "Reverse", time: "O(n)" },
      { op: "Detect cycle", time: "O(n)" },
    ],
    commonMistakes: [
      "Losing the next pointer before reassigning",
      "Not returning the new head after reversing",
      "Forgetting the dummy node trick for insert/delete at head",
      "Infinite loop when detecting cycle without slow/fast",
    ],
    memoryTricks: [
      "Use a dummy head to avoid special-casing insertions",
      "Slow/fast pointers = cycle & middle in one pass",
      "Reverse-in-place: 3 pointers (prev, cur, next)",
    ],
    mustSolve: ["q-ll-reverse", "q-ll-cycle", "q-ll-merge", "q-ll-middle"],
  },
  questions: [
    {
      id: "q-ll-what-is",
      moduleSlug: "linked-lists",
      title: "Linked list vs array — when to use which?",
      category: "theory",
      difficulty: "Beginner",
      topic: "Fundamentals",
      description: "Compare memory layout, access patterns, and insertion cost.",
      hints: ["Arrays: contiguous memory, O(1) random access, O(n) insertion in the middle. Lists: pointers, O(1) head insert, O(n) access."],
      estimatedMinutes: 5,
      tags: ["theory"],
      interviewFrequency: "High",
    },
    {
      id: "q-ll-reverse",
      moduleSlug: "linked-lists",
      title: "Reverse a linked list",
      category: "implementation",
      difficulty: "Interview",
      topic: "Reversal",
      description: "Reverse a singly linked list iteratively and recursively.",
      hints: ["Three-pointer swap: prev, cur, next."],
      approaches: [
        {
          name: "Optimal",
          code: "def reverse(head):\n    prev, cur = None, head\n    while cur:\n        cur.next, prev, cur = prev, cur, cur.next\n    return prev",
          time: "O(n)",
          space: "O(1)",
        },
        {
          name: "Better",
          code: "def reverse(head, prev=None):\n    if not head: return prev\n    nxt = head.next\n    head.next = prev\n    return reverse(nxt, head)",
          time: "O(n)",
          space: "O(n)",
          note: "Recursion uses the call stack.",
        },
      ],
      visualizationType: "linked-list",
      estimatedMinutes: 15,
      pattern: "Two Pointers",
      companies: ["Amazon", "Microsoft", "Meta"],
      interviewFrequency: "Very High",
      leetcodeLinks: [{ title: "206. Reverse Linked List", url: "https://leetcode.com/problems/reverse-linked-list/", difficulty: "Easy" }],
      relatedQuestions: ["q-ll-merge", "q-ll-middle"],
      tags: ["must-do"],
    },
    {
      id: "q-ll-cycle",
      moduleSlug: "linked-lists",
      title: "Detect a cycle (Floyd's tortoise & hare)",
      category: "intermediate",
      difficulty: "Interview",
      topic: "Cycle Detection",
      description: "Return True if the linked list has a cycle.",
      hints: ["Two pointers at different speeds.", "If they meet, there's a cycle."],
      approaches: [
        {
          name: "Brute",
          code: "seen = set()\nwhile head:\n    if head in seen: return True\n    seen.add(head)\n    head = head.next\nreturn False",
          time: "O(n)",
          space: "O(n)",
        },
        {
          name: "Optimal",
          code: "slow = fast = head\nwhile fast and fast.next:\n    slow = slow.next\n    fast = fast.next.next\n    if slow is fast: return True\nreturn False",
          time: "O(n)",
          space: "O(1)",
        },
      ],
      estimatedMinutes: 15,
      pattern: "Two Pointers",
      companies: ["Amazon", "Google"],
      interviewFrequency: "Very High",
      leetcodeLinks: [{ title: "141. Linked List Cycle", url: "https://leetcode.com/problems/linked-list-cycle/", difficulty: "Easy" }],
      tags: ["must-do", "floyd"],
    },
    {
      id: "q-ll-middle",
      moduleSlug: "linked-lists",
      title: "Find the middle node",
      category: "implementation",
      difficulty: "Beginner",
      topic: "Two Pointers",
      description: "Return the middle node in one pass.",
      approaches: [
        {
          name: "Optimal",
          code: "slow = fast = head\nwhile fast and fast.next:\n    slow = slow.next\n    fast = fast.next.next\nreturn slow",
          time: "O(n)",
          space: "O(1)",
        },
      ],
      estimatedMinutes: 10,
      pattern: "Two Pointers",
      interviewFrequency: "High",
      leetcodeLinks: [{ title: "876. Middle of the Linked List", url: "https://leetcode.com/problems/middle-of-the-linked-list/", difficulty: "Easy" }],
    },
    {
      id: "q-ll-merge",
      moduleSlug: "linked-lists",
      title: "Merge two sorted linked lists",
      category: "intermediate",
      difficulty: "Interview",
      topic: "Merging",
      description: "Merge two sorted lists into a single sorted list.",
      hints: ["Use a dummy head.", "Pick the smaller head at each step."],
      approaches: [
        {
          name: "Optimal",
          code: "def merge(a, b):\n    dummy = tail = ListNode(0)\n    while a and b:\n        if a.val <= b.val:\n            tail.next, a = a, a.next\n        else:\n            tail.next, b = b, b.next\n        tail = tail.next\n    tail.next = a or b\n    return dummy.next",
          time: "O(n + m)",
          space: "O(1)",
        },
      ],
      estimatedMinutes: 15,
      pattern: "Merge",
      interviewFrequency: "Very High",
      leetcodeLinks: [{ title: "21. Merge Two Sorted Lists", url: "https://leetcode.com/problems/merge-two-sorted-lists/", difficulty: "Easy" }],
      tags: ["must-do", "dummy-head"],
    },
    {
      id: "q-ll-remove-nth",
      moduleSlug: "linked-lists",
      title: "Remove Nth node from end",
      category: "intermediate",
      difficulty: "Interview",
      topic: "Two Pointers",
      description: "Remove the nth node from the end in one pass.",
      hints: ["Advance fast pointer n steps first, then move both."],
      approaches: [
        {
          name: "Optimal",
          code: "dummy = ListNode(0, head)\nfast = slow = dummy\nfor _ in range(n): fast = fast.next\nwhile fast.next:\n    fast, slow = fast.next, slow.next\nslow.next = slow.next.next\nreturn dummy.next",
          time: "O(n)",
          space: "O(1)",
        },
      ],
      estimatedMinutes: 20,
      pattern: "Two Pointers",
      interviewFrequency: "High",
      leetcodeLinks: [{ title: "19. Remove Nth Node From End", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", difficulty: "Medium" }],
    },
    {
      id: "q-ll-edge-head-delete",
      moduleSlug: "linked-lists",
      title: "Deleting the head safely",
      category: "edge-case",
      difficulty: "Beginner",
      topic: "Edge Cases",
      description: "Show how a dummy node eliminates the special case when the target is at the head.",
      pythonSolution: "dummy = ListNode(0, head)\nprev = dummy\nwhile prev.next:\n    if prev.next.val == target:\n        prev.next = prev.next.next\n    else:\n        prev = prev.next\nreturn dummy.next",
      estimatedMinutes: 5,
      tags: ["dummy-head", "edge"],
    },
  ],
};
