import type { ModuleBank } from "../types";

export const treesBank: ModuleBank = {
  moduleSlug: "trees",
  moduleTitle: "Trees",
  edgeCases: [
    { case: "Empty tree", why: "root is None — return 0 / [] / True as appropriate." },
    { case: "Single node", why: "Depth 1, no children." },
    { case: "Skewed tree", why: "Behaves like a linked list — recursion depth = n → risk of stack overflow." },
    { case: "Duplicate values", why: "Validate BST logic must allow (or forbid) duplicates consistently." },
  ],
  revisionSheet: {
    timeComplexity: [
      { op: "Traversal (pre/in/post/level)", time: "O(n)" },
      { op: "Height", time: "O(n)" },
      { op: "LCA (naive)", time: "O(n)" },
      { op: "BST search (balanced)", time: "O(log n)" },
    ],
    commonMistakes: [
      "Using DFS recursion on very deep trees — hits Python's recursion limit",
      "Mixing pre-order and in-order in serialization",
      "Off-by-one in level-order — appending Nones for missing children",
    ],
    memoryTricks: [
      "In-order of a BST → sorted",
      "Level-order = BFS = queue",
      "Post-order = process children before node → good for cleanup",
    ],
    mustSolve: ["q-tr-invert", "q-tr-max-depth", "q-tr-level-order", "q-tr-lca"],
  },
  questions: [
    {
      id: "q-tr-traversals",
      moduleSlug: "trees",
      title: "Compare the four traversals",
      category: "theory",
      difficulty: "Beginner",
      topic: "Traversal",
      description: "Pre-order, in-order, post-order, and level-order — when to use each?",
      pythonSolution:
        "def preorder(r): return [r.val] + preorder(r.left) + preorder(r.right) if r else []\ndef inorder(r): return inorder(r.left) + [r.val] + inorder(r.right) if r else []\ndef postorder(r): return postorder(r.left) + postorder(r.right) + [r.val] if r else []",
      estimatedMinutes: 10,
      tags: ["theory"],
    },
    {
      id: "q-tr-max-depth",
      moduleSlug: "trees",
      title: "Maximum Depth of Binary Tree",
      category: "implementation",
      difficulty: "Beginner",
      topic: "DFS",
      description: "Return the length of the longest root-to-leaf path.",
      approaches: [
        {
          name: "Optimal",
          code: "def max_depth(r):\n    if not r: return 0\n    return 1 + max(max_depth(r.left), max_depth(r.right))",
          time: "O(n)",
          space: "O(h)",
        },
      ],
      leetcodeLinks: [{ title: "104. Maximum Depth of Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "Easy" }],
      estimatedMinutes: 10,
      interviewFrequency: "Very High",
      pattern: "DFS",
      tags: ["must-do"],
    },
    {
      id: "q-tr-invert",
      moduleSlug: "trees",
      title: "Invert Binary Tree",
      category: "implementation",
      difficulty: "Interview",
      topic: "DFS",
      description: "Swap left and right subtrees for every node.",
      pythonSolution: "def invert(r):\n    if not r: return None\n    r.left, r.right = invert(r.right), invert(r.left)\n    return r",
      leetcodeLinks: [{ title: "226. Invert Binary Tree", url: "https://leetcode.com/problems/invert-binary-tree/", difficulty: "Easy" }],
      estimatedMinutes: 5,
      interviewFrequency: "Very High",
      companies: ["Google"],
      tags: ["must-do"],
    },
    {
      id: "q-tr-level-order",
      moduleSlug: "trees",
      title: "Level Order Traversal (BFS)",
      category: "intermediate",
      difficulty: "Interview",
      topic: "BFS",
      description: "Return nodes level by level.",
      approaches: [
        {
          name: "Optimal",
          code: "from collections import deque\nif not root: return []\nq, res = deque([root]), []\nwhile q:\n    level = []\n    for _ in range(len(q)):\n        n = q.popleft(); level.append(n.val)\n        if n.left: q.append(n.left)\n        if n.right: q.append(n.right)\n    res.append(level)\nreturn res",
          time: "O(n)",
          space: "O(n)",
        },
      ],
      leetcodeLinks: [{ title: "102. Binary Tree Level Order Traversal", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", difficulty: "Medium" }],
      interviewFrequency: "Very High",
      pattern: "BFS",
      estimatedMinutes: 15,
      tags: ["must-do"],
    },
    {
      id: "q-tr-lca",
      moduleSlug: "trees",
      title: "Lowest Common Ancestor of a Binary Tree",
      category: "advanced",
      difficulty: "Interview",
      topic: "Recursion",
      description: "Return the LCA of two given nodes.",
      approaches: [
        {
          name: "Optimal",
          code: "def lca(root, p, q):\n    if not root or root is p or root is q: return root\n    left = lca(root.left, p, q)\n    right = lca(root.right, p, q)\n    return root if left and right else left or right",
          time: "O(n)",
          space: "O(h)",
        },
      ],
      leetcodeLinks: [{ title: "236. Lowest Common Ancestor", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", difficulty: "Medium" }],
      interviewFrequency: "Very High",
      companies: ["Meta", "Amazon"],
      estimatedMinutes: 25,
      tags: ["must-do", "recursion"],
    },
  ],
};
