/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraversingRouteImport } from './routes/traversing'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as SlicingRouteImport } from './routes/slicing'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NestedRouteImport } from './routes/nested'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as InsertionRouteImport } from './routes/insertion'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeletionRouteImport } from './routes/deletion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatingRouteImport } from './routes/creating'
import { Route as CopyingRouteImport } from './routes/copying'
import { Route as ComprehensionRouteImport } from './routes/comprehension'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as ArrayVsListRouteImport } from './routes/array-vs-list'
import { Route as AccessingRouteImport } from './routes/accessing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PlaygroundsIndexRouteImport } from './routes/playgrounds.index'
import { Route as GraphsIndexRouteImport } from './routes/graphs.index'
import { Route as ComplexityIndexRouteImport } from './routes/complexity.index'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms.index'
import { Route as TreesSplatRouteImport } from './routes/trees.$'
import { Route as StacksInterviewRouteImport } from './routes/stacks.interview'
import { Route as StacksFaqRouteImport } from './routes/stacks.faq'
import { Route as StacksSplatRouteImport } from './routes/stacks.$'
import { Route as QueuesInterviewRouteImport } from './routes/queues.interview'
import { Route as QueuesFaqRouteImport } from './routes/queues.faq'
import { Route as QueuesSplatRouteImport } from './routes/queues.$'
import { Route as PlaygroundsSortingRouteImport } from './routes/playgrounds.sorting'
import { Route as PlaygroundsSearchingRouteImport } from './routes/playgrounds.searching'
import { Route as PlaygroundsRecursionRouteImport } from './routes/playgrounds.recursion'
import { Route as PlaygroundsGraphRouteImport } from './routes/playgrounds.graph'
import { Route as PlaygroundsDivideConquerRouteImport } from './routes/playgrounds.divide-conquer'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as LinkedListsInterviewRouteImport } from './routes/linked-lists.interview'
import { Route as LinkedListsFaqRouteImport } from './routes/linked-lists.faq'
import { Route as LinkedListsSplatRouteImport } from './routes/linked-lists.$'
import { Route as HeapsSplatRouteImport } from './routes/heaps.$'
import { Route as HashTablesSplatRouteImport } from './routes/hash-tables.$'
import { Route as GraphsSplatRouteImport } from './routes/graphs.$'
import { Route as ComplexityTimeRouteImport } from './routes/complexity.time'
import { Route as ComplexitySpaceRouteImport } from './routes/complexity.space'
import { Route as AlgorithmsSlugRouteImport } from './routes/algorithms.$slug'
import { Route as LearnCourseIndexRouteImport } from './routes/learn.$course.index'
import { Route as LearnCourseLessonRouteImport } from './routes/learn.$course.$lesson'

const TraversingRoute = TraversingRouteImport.update({
  id: '/traversing',
  path: '/traversing',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const SlicingRoute = SlicingRouteImport.update({
  id: '/slicing',
  path: '/slicing',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedRoute = NestedRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const InsertionRoute = InsertionRouteImport.update({
  id: '/insertion',
  path: '/insertion',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletionRoute = DeletionRouteImport.update({
  id: '/deletion',
  path: '/deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatingRoute = CreatingRouteImport.update({
  id: '/creating',
  path: '/creating',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyingRoute = CopyingRouteImport.update({
  id: '/copying',
  path: '/copying',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprehensionRoute = ComprehensionRouteImport.update({
  id: '/comprehension',
  path: '/comprehension',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrayVsListRoute = ArrayVsListRouteImport.update({
  id: '/array-vs-list',
  path: '/array-vs-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessingRoute = AccessingRouteImport.update({
  id: '/accessing',
  path: '/accessing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsIndexRoute = PlaygroundsIndexRouteImport.update({
  id: '/playgrounds/',
  path: '/playgrounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsIndexRoute = GraphsIndexRouteImport.update({
  id: '/graphs/',
  path: '/graphs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexityIndexRoute = ComplexityIndexRouteImport.update({
  id: '/complexity/',
  path: '/complexity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreesSplatRoute = TreesSplatRouteImport.update({
  id: '/trees/$',
  path: '/trees/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksInterviewRoute = StacksInterviewRouteImport.update({
  id: '/stacks/interview',
  path: '/stacks/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksFaqRoute = StacksFaqRouteImport.update({
  id: '/stacks/faq',
  path: '/stacks/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSplatRoute = StacksSplatRouteImport.update({
  id: '/stacks/$',
  path: '/stacks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesInterviewRoute = QueuesInterviewRouteImport.update({
  id: '/queues/interview',
  path: '/queues/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesFaqRoute = QueuesFaqRouteImport.update({
  id: '/queues/faq',
  path: '/queues/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesSplatRoute = QueuesSplatRouteImport.update({
  id: '/queues/$',
  path: '/queues/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsSortingRoute = PlaygroundsSortingRouteImport.update({
  id: '/playgrounds/sorting',
  path: '/playgrounds/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsSearchingRoute = PlaygroundsSearchingRouteImport.update({
  id: '/playgrounds/searching',
  path: '/playgrounds/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsRecursionRoute = PlaygroundsRecursionRouteImport.update({
  id: '/playgrounds/recursion',
  path: '/playgrounds/recursion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsGraphRoute = PlaygroundsGraphRouteImport.update({
  id: '/playgrounds/graph',
  path: '/playgrounds/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundsDivideConquerRoute =
  PlaygroundsDivideConquerRouteImport.update({
    id: '/playgrounds/divide-conquer',
    path: '/playgrounds/divide-conquer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedListsInterviewRoute = LinkedListsInterviewRouteImport.update({
  id: '/linked-lists/interview',
  path: '/linked-lists/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedListsFaqRoute = LinkedListsFaqRouteImport.update({
  id: '/linked-lists/faq',
  path: '/linked-lists/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedListsSplatRoute = LinkedListsSplatRouteImport.update({
  id: '/linked-lists/$',
  path: '/linked-lists/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HeapsSplatRoute = HeapsSplatRouteImport.update({
  id: '/heaps/$',
  path: '/heaps/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HashTablesSplatRoute = HashTablesSplatRouteImport.update({
  id: '/hash-tables/$',
  path: '/hash-tables/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsSplatRoute = GraphsSplatRouteImport.update({
  id: '/graphs/$',
  path: '/graphs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexityTimeRoute = ComplexityTimeRouteImport.update({
  id: '/complexity/time',
  path: '/complexity/time',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexitySpaceRoute = ComplexitySpaceRouteImport.update({
  id: '/complexity/space',
  path: '/complexity/space',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSlugRoute = AlgorithmsSlugRouteImport.update({
  id: '/algorithms/$slug',
  path: '/algorithms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIndexRoute = LearnCourseIndexRouteImport.update({
  id: '/learn/$course/',
  path: '/learn/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseLessonRoute = LearnCourseLessonRouteImport.update({
  id: '/learn/$course/$lesson',
  path: '/learn/$course/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessing': typeof AccessingRoute
  '/array-vs-list': typeof ArrayVsListRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/comprehension': typeof ComprehensionRoute
  '/copying': typeof CopyingRoute
  '/creating': typeof CreatingRoute
  '/dashboard': typeof DashboardRoute
  '/deletion': typeof DeletionRoute
  '/faq': typeof FaqRoute
  '/insertion': typeof InsertionRoute
  '/introduction': typeof IntroductionRoute
  '/methods': typeof MethodsRoute
  '/nested': typeof NestedRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/slicing': typeof SlicingRoute
  '/sorting': typeof SortingRoute
  '/traversing': typeof TraversingRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/complexity/space': typeof ComplexitySpaceRoute
  '/complexity/time': typeof ComplexityTimeRoute
  '/graphs/$': typeof GraphsSplatRoute
  '/hash-tables/$': typeof HashTablesSplatRoute
  '/heaps/$': typeof HeapsSplatRoute
  '/linked-lists/$': typeof LinkedListsSplatRoute
  '/linked-lists/faq': typeof LinkedListsFaqRoute
  '/linked-lists/interview': typeof LinkedListsInterviewRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/playgrounds/divide-conquer': typeof PlaygroundsDivideConquerRoute
  '/playgrounds/graph': typeof PlaygroundsGraphRoute
  '/playgrounds/recursion': typeof PlaygroundsRecursionRoute
  '/playgrounds/searching': typeof PlaygroundsSearchingRoute
  '/playgrounds/sorting': typeof PlaygroundsSortingRoute
  '/queues/$': typeof QueuesSplatRoute
  '/queues/faq': typeof QueuesFaqRoute
  '/queues/interview': typeof QueuesInterviewRoute
  '/stacks/$': typeof StacksSplatRoute
  '/stacks/faq': typeof StacksFaqRoute
  '/stacks/interview': typeof StacksInterviewRoute
  '/trees/$': typeof TreesSplatRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/complexity/': typeof ComplexityIndexRoute
  '/graphs/': typeof GraphsIndexRoute
  '/playgrounds/': typeof PlaygroundsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/learn/$course/$lesson': typeof LearnCourseLessonRoute
  '/learn/$course/': typeof LearnCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessing': typeof AccessingRoute
  '/array-vs-list': typeof ArrayVsListRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/comprehension': typeof ComprehensionRoute
  '/copying': typeof CopyingRoute
  '/creating': typeof CreatingRoute
  '/dashboard': typeof DashboardRoute
  '/deletion': typeof DeletionRoute
  '/faq': typeof FaqRoute
  '/insertion': typeof InsertionRoute
  '/introduction': typeof IntroductionRoute
  '/methods': typeof MethodsRoute
  '/nested': typeof NestedRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/slicing': typeof SlicingRoute
  '/sorting': typeof SortingRoute
  '/traversing': typeof TraversingRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/complexity/space': typeof ComplexitySpaceRoute
  '/complexity/time': typeof ComplexityTimeRoute
  '/graphs/$': typeof GraphsSplatRoute
  '/hash-tables/$': typeof HashTablesSplatRoute
  '/heaps/$': typeof HeapsSplatRoute
  '/linked-lists/$': typeof LinkedListsSplatRoute
  '/linked-lists/faq': typeof LinkedListsFaqRoute
  '/linked-lists/interview': typeof LinkedListsInterviewRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/playgrounds/divide-conquer': typeof PlaygroundsDivideConquerRoute
  '/playgrounds/graph': typeof PlaygroundsGraphRoute
  '/playgrounds/recursion': typeof PlaygroundsRecursionRoute
  '/playgrounds/searching': typeof PlaygroundsSearchingRoute
  '/playgrounds/sorting': typeof PlaygroundsSortingRoute
  '/queues/$': typeof QueuesSplatRoute
  '/queues/faq': typeof QueuesFaqRoute
  '/queues/interview': typeof QueuesInterviewRoute
  '/stacks/$': typeof StacksSplatRoute
  '/stacks/faq': typeof StacksFaqRoute
  '/stacks/interview': typeof StacksInterviewRoute
  '/trees/$': typeof TreesSplatRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/complexity': typeof ComplexityIndexRoute
  '/graphs': typeof GraphsIndexRoute
  '/playgrounds': typeof PlaygroundsIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/learn/$course/$lesson': typeof LearnCourseLessonRoute
  '/learn/$course': typeof LearnCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessing': typeof AccessingRoute
  '/array-vs-list': typeof ArrayVsListRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/comprehension': typeof ComprehensionRoute
  '/copying': typeof CopyingRoute
  '/creating': typeof CreatingRoute
  '/dashboard': typeof DashboardRoute
  '/deletion': typeof DeletionRoute
  '/faq': typeof FaqRoute
  '/insertion': typeof InsertionRoute
  '/introduction': typeof IntroductionRoute
  '/methods': typeof MethodsRoute
  '/nested': typeof NestedRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/slicing': typeof SlicingRoute
  '/sorting': typeof SortingRoute
  '/traversing': typeof TraversingRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/complexity/space': typeof ComplexitySpaceRoute
  '/complexity/time': typeof ComplexityTimeRoute
  '/graphs/$': typeof GraphsSplatRoute
  '/hash-tables/$': typeof HashTablesSplatRoute
  '/heaps/$': typeof HeapsSplatRoute
  '/linked-lists/$': typeof LinkedListsSplatRoute
  '/linked-lists/faq': typeof LinkedListsFaqRoute
  '/linked-lists/interview': typeof LinkedListsInterviewRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/playgrounds/divide-conquer': typeof PlaygroundsDivideConquerRoute
  '/playgrounds/graph': typeof PlaygroundsGraphRoute
  '/playgrounds/recursion': typeof PlaygroundsRecursionRoute
  '/playgrounds/searching': typeof PlaygroundsSearchingRoute
  '/playgrounds/sorting': typeof PlaygroundsSortingRoute
  '/queues/$': typeof QueuesSplatRoute
  '/queues/faq': typeof QueuesFaqRoute
  '/queues/interview': typeof QueuesInterviewRoute
  '/stacks/$': typeof StacksSplatRoute
  '/stacks/faq': typeof StacksFaqRoute
  '/stacks/interview': typeof StacksInterviewRoute
  '/trees/$': typeof TreesSplatRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/complexity/': typeof ComplexityIndexRoute
  '/graphs/': typeof GraphsIndexRoute
  '/playgrounds/': typeof PlaygroundsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/learn/$course/$lesson': typeof LearnCourseLessonRoute
  '/learn/$course/': typeof LearnCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessing'
    | '/array-vs-list'
    | '/cheatsheet'
    | '/comprehension'
    | '/copying'
    | '/creating'
    | '/dashboard'
    | '/deletion'
    | '/faq'
    | '/insertion'
    | '/introduction'
    | '/methods'
    | '/nested'
    | '/resources'
    | '/roadmap'
    | '/search'
    | '/searching'
    | '/slicing'
    | '/sorting'
    | '/traversing'
    | '/algorithms/$slug'
    | '/complexity/space'
    | '/complexity/time'
    | '/graphs/$'
    | '/hash-tables/$'
    | '/heaps/$'
    | '/linked-lists/$'
    | '/linked-lists/faq'
    | '/linked-lists/interview'
    | '/modules/$slug'
    | '/playgrounds/divide-conquer'
    | '/playgrounds/graph'
    | '/playgrounds/recursion'
    | '/playgrounds/searching'
    | '/playgrounds/sorting'
    | '/queues/$'
    | '/queues/faq'
    | '/queues/interview'
    | '/stacks/$'
    | '/stacks/faq'
    | '/stacks/interview'
    | '/trees/$'
    | '/algorithms/'
    | '/complexity/'
    | '/graphs/'
    | '/playgrounds/'
    | '/practice/'
    | '/learn/$course/$lesson'
    | '/learn/$course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessing'
    | '/array-vs-list'
    | '/cheatsheet'
    | '/comprehension'
    | '/copying'
    | '/creating'
    | '/dashboard'
    | '/deletion'
    | '/faq'
    | '/insertion'
    | '/introduction'
    | '/methods'
    | '/nested'
    | '/resources'
    | '/roadmap'
    | '/search'
    | '/searching'
    | '/slicing'
    | '/sorting'
    | '/traversing'
    | '/algorithms/$slug'
    | '/complexity/space'
    | '/complexity/time'
    | '/graphs/$'
    | '/hash-tables/$'
    | '/heaps/$'
    | '/linked-lists/$'
    | '/linked-lists/faq'
    | '/linked-lists/interview'
    | '/modules/$slug'
    | '/playgrounds/divide-conquer'
    | '/playgrounds/graph'
    | '/playgrounds/recursion'
    | '/playgrounds/searching'
    | '/playgrounds/sorting'
    | '/queues/$'
    | '/queues/faq'
    | '/queues/interview'
    | '/stacks/$'
    | '/stacks/faq'
    | '/stacks/interview'
    | '/trees/$'
    | '/algorithms'
    | '/complexity'
    | '/graphs'
    | '/playgrounds'
    | '/practice'
    | '/learn/$course/$lesson'
    | '/learn/$course'
  id:
    | '__root__'
    | '/'
    | '/accessing'
    | '/array-vs-list'
    | '/cheatsheet'
    | '/comprehension'
    | '/copying'
    | '/creating'
    | '/dashboard'
    | '/deletion'
    | '/faq'
    | '/insertion'
    | '/introduction'
    | '/methods'
    | '/nested'
    | '/resources'
    | '/roadmap'
    | '/search'
    | '/searching'
    | '/slicing'
    | '/sorting'
    | '/traversing'
    | '/algorithms/$slug'
    | '/complexity/space'
    | '/complexity/time'
    | '/graphs/$'
    | '/hash-tables/$'
    | '/heaps/$'
    | '/linked-lists/$'
    | '/linked-lists/faq'
    | '/linked-lists/interview'
    | '/modules/$slug'
    | '/playgrounds/divide-conquer'
    | '/playgrounds/graph'
    | '/playgrounds/recursion'
    | '/playgrounds/searching'
    | '/playgrounds/sorting'
    | '/queues/$'
    | '/queues/faq'
    | '/queues/interview'
    | '/stacks/$'
    | '/stacks/faq'
    | '/stacks/interview'
    | '/trees/$'
    | '/algorithms/'
    | '/complexity/'
    | '/graphs/'
    | '/playgrounds/'
    | '/practice/'
    | '/learn/$course/$lesson'
    | '/learn/$course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessingRoute: typeof AccessingRoute
  ArrayVsListRoute: typeof ArrayVsListRoute
  CheatsheetRoute: typeof CheatsheetRoute
  ComprehensionRoute: typeof ComprehensionRoute
  CopyingRoute: typeof CopyingRoute
  CreatingRoute: typeof CreatingRoute
  DashboardRoute: typeof DashboardRoute
  DeletionRoute: typeof DeletionRoute
  FaqRoute: typeof FaqRoute
  InsertionRoute: typeof InsertionRoute
  IntroductionRoute: typeof IntroductionRoute
  MethodsRoute: typeof MethodsRoute
  NestedRoute: typeof NestedRoute
  ResourcesRoute: typeof ResourcesRoute
  RoadmapRoute: typeof RoadmapRoute
  SearchRoute: typeof SearchRoute
  SearchingRoute: typeof SearchingRoute
  SlicingRoute: typeof SlicingRoute
  SortingRoute: typeof SortingRoute
  TraversingRoute: typeof TraversingRoute
  AlgorithmsSlugRoute: typeof AlgorithmsSlugRoute
  ComplexitySpaceRoute: typeof ComplexitySpaceRoute
  ComplexityTimeRoute: typeof ComplexityTimeRoute
  GraphsSplatRoute: typeof GraphsSplatRoute
  HashTablesSplatRoute: typeof HashTablesSplatRoute
  HeapsSplatRoute: typeof HeapsSplatRoute
  LinkedListsSplatRoute: typeof LinkedListsSplatRoute
  LinkedListsFaqRoute: typeof LinkedListsFaqRoute
  LinkedListsInterviewRoute: typeof LinkedListsInterviewRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  PlaygroundsDivideConquerRoute: typeof PlaygroundsDivideConquerRoute
  PlaygroundsGraphRoute: typeof PlaygroundsGraphRoute
  PlaygroundsRecursionRoute: typeof PlaygroundsRecursionRoute
  PlaygroundsSearchingRoute: typeof PlaygroundsSearchingRoute
  PlaygroundsSortingRoute: typeof PlaygroundsSortingRoute
  QueuesSplatRoute: typeof QueuesSplatRoute
  QueuesFaqRoute: typeof QueuesFaqRoute
  QueuesInterviewRoute: typeof QueuesInterviewRoute
  StacksSplatRoute: typeof StacksSplatRoute
  StacksFaqRoute: typeof StacksFaqRoute
  StacksInterviewRoute: typeof StacksInterviewRoute
  TreesSplatRoute: typeof TreesSplatRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
  ComplexityIndexRoute: typeof ComplexityIndexRoute
  GraphsIndexRoute: typeof GraphsIndexRoute
  PlaygroundsIndexRoute: typeof PlaygroundsIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  LearnCourseLessonRoute: typeof LearnCourseLessonRoute
  LearnCourseIndexRoute: typeof LearnCourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traversing': {
      id: '/traversing'
      path: '/traversing'
      fullPath: '/traversing'
      preLoaderRoute: typeof TraversingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slicing': {
      id: '/slicing'
      path: '/slicing'
      fullPath: '/slicing'
      preLoaderRoute: typeof SlicingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested': {
      id: '/nested'
      path: '/nested'
      fullPath: '/nested'
      preLoaderRoute: typeof NestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insertion': {
      id: '/insertion'
      path: '/insertion'
      fullPath: '/insertion'
      preLoaderRoute: typeof InsertionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deletion': {
      id: '/deletion'
      path: '/deletion'
      fullPath: '/deletion'
      preLoaderRoute: typeof DeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creating': {
      id: '/creating'
      path: '/creating'
      fullPath: '/creating'
      preLoaderRoute: typeof CreatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copying': {
      id: '/copying'
      path: '/copying'
      fullPath: '/copying'
      preLoaderRoute: typeof CopyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprehension': {
      id: '/comprehension'
      path: '/comprehension'
      fullPath: '/comprehension'
      preLoaderRoute: typeof ComprehensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/array-vs-list': {
      id: '/array-vs-list'
      path: '/array-vs-list'
      fullPath: '/array-vs-list'
      preLoaderRoute: typeof ArrayVsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessing': {
      id: '/accessing'
      path: '/accessing'
      fullPath: '/accessing'
      preLoaderRoute: typeof AccessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/': {
      id: '/playgrounds/'
      path: '/playgrounds'
      fullPath: '/playgrounds/'
      preLoaderRoute: typeof PlaygroundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/': {
      id: '/graphs/'
      path: '/graphs'
      fullPath: '/graphs/'
      preLoaderRoute: typeof GraphsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexity/': {
      id: '/complexity/'
      path: '/complexity'
      fullPath: '/complexity/'
      preLoaderRoute: typeof ComplexityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trees/$': {
      id: '/trees/$'
      path: '/trees/$'
      fullPath: '/trees/$'
      preLoaderRoute: typeof TreesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/interview': {
      id: '/stacks/interview'
      path: '/stacks/interview'
      fullPath: '/stacks/interview'
      preLoaderRoute: typeof StacksInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/faq': {
      id: '/stacks/faq'
      path: '/stacks/faq'
      fullPath: '/stacks/faq'
      preLoaderRoute: typeof StacksFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$': {
      id: '/stacks/$'
      path: '/stacks/$'
      fullPath: '/stacks/$'
      preLoaderRoute: typeof StacksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/interview': {
      id: '/queues/interview'
      path: '/queues/interview'
      fullPath: '/queues/interview'
      preLoaderRoute: typeof QueuesInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/faq': {
      id: '/queues/faq'
      path: '/queues/faq'
      fullPath: '/queues/faq'
      preLoaderRoute: typeof QueuesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$': {
      id: '/queues/$'
      path: '/queues/$'
      fullPath: '/queues/$'
      preLoaderRoute: typeof QueuesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/sorting': {
      id: '/playgrounds/sorting'
      path: '/playgrounds/sorting'
      fullPath: '/playgrounds/sorting'
      preLoaderRoute: typeof PlaygroundsSortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/searching': {
      id: '/playgrounds/searching'
      path: '/playgrounds/searching'
      fullPath: '/playgrounds/searching'
      preLoaderRoute: typeof PlaygroundsSearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/recursion': {
      id: '/playgrounds/recursion'
      path: '/playgrounds/recursion'
      fullPath: '/playgrounds/recursion'
      preLoaderRoute: typeof PlaygroundsRecursionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/graph': {
      id: '/playgrounds/graph'
      path: '/playgrounds/graph'
      fullPath: '/playgrounds/graph'
      preLoaderRoute: typeof PlaygroundsGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playgrounds/divide-conquer': {
      id: '/playgrounds/divide-conquer'
      path: '/playgrounds/divide-conquer'
      fullPath: '/playgrounds/divide-conquer'
      preLoaderRoute: typeof PlaygroundsDivideConquerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-lists/interview': {
      id: '/linked-lists/interview'
      path: '/linked-lists/interview'
      fullPath: '/linked-lists/interview'
      preLoaderRoute: typeof LinkedListsInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-lists/faq': {
      id: '/linked-lists/faq'
      path: '/linked-lists/faq'
      fullPath: '/linked-lists/faq'
      preLoaderRoute: typeof LinkedListsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-lists/$': {
      id: '/linked-lists/$'
      path: '/linked-lists/$'
      fullPath: '/linked-lists/$'
      preLoaderRoute: typeof LinkedListsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heaps/$': {
      id: '/heaps/$'
      path: '/heaps/$'
      fullPath: '/heaps/$'
      preLoaderRoute: typeof HeapsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-tables/$': {
      id: '/hash-tables/$'
      path: '/hash-tables/$'
      fullPath: '/hash-tables/$'
      preLoaderRoute: typeof HashTablesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$': {
      id: '/graphs/$'
      path: '/graphs/$'
      fullPath: '/graphs/$'
      preLoaderRoute: typeof GraphsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexity/time': {
      id: '/complexity/time'
      path: '/complexity/time'
      fullPath: '/complexity/time'
      preLoaderRoute: typeof ComplexityTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexity/space': {
      id: '/complexity/space'
      path: '/complexity/space'
      fullPath: '/complexity/space'
      preLoaderRoute: typeof ComplexitySpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$slug': {
      id: '/algorithms/$slug'
      path: '/algorithms/$slug'
      fullPath: '/algorithms/$slug'
      preLoaderRoute: typeof AlgorithmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$course/': {
      id: '/learn/$course/'
      path: '/learn/$course'
      fullPath: '/learn/$course/'
      preLoaderRoute: typeof LearnCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$course/$lesson': {
      id: '/learn/$course/$lesson'
      path: '/learn/$course/$lesson'
      fullPath: '/learn/$course/$lesson'
      preLoaderRoute: typeof LearnCourseLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessingRoute: AccessingRoute,
  ArrayVsListRoute: ArrayVsListRoute,
  CheatsheetRoute: CheatsheetRoute,
  ComprehensionRoute: ComprehensionRoute,
  CopyingRoute: CopyingRoute,
  CreatingRoute: CreatingRoute,
  DashboardRoute: DashboardRoute,
  DeletionRoute: DeletionRoute,
  FaqRoute: FaqRoute,
  InsertionRoute: InsertionRoute,
  IntroductionRoute: IntroductionRoute,
  MethodsRoute: MethodsRoute,
  NestedRoute: NestedRoute,
  ResourcesRoute: ResourcesRoute,
  RoadmapRoute: RoadmapRoute,
  SearchRoute: SearchRoute,
  SearchingRoute: SearchingRoute,
  SlicingRoute: SlicingRoute,
  SortingRoute: SortingRoute,
  TraversingRoute: TraversingRoute,
  AlgorithmsSlugRoute: AlgorithmsSlugRoute,
  ComplexitySpaceRoute: ComplexitySpaceRoute,
  ComplexityTimeRoute: ComplexityTimeRoute,
  GraphsSplatRoute: GraphsSplatRoute,
  HashTablesSplatRoute: HashTablesSplatRoute,
  HeapsSplatRoute: HeapsSplatRoute,
  LinkedListsSplatRoute: LinkedListsSplatRoute,
  LinkedListsFaqRoute: LinkedListsFaqRoute,
  LinkedListsInterviewRoute: LinkedListsInterviewRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  PlaygroundsDivideConquerRoute: PlaygroundsDivideConquerRoute,
  PlaygroundsGraphRoute: PlaygroundsGraphRoute,
  PlaygroundsRecursionRoute: PlaygroundsRecursionRoute,
  PlaygroundsSearchingRoute: PlaygroundsSearchingRoute,
  PlaygroundsSortingRoute: PlaygroundsSortingRoute,
  QueuesSplatRoute: QueuesSplatRoute,
  QueuesFaqRoute: QueuesFaqRoute,
  QueuesInterviewRoute: QueuesInterviewRoute,
  StacksSplatRoute: StacksSplatRoute,
  StacksFaqRoute: StacksFaqRoute,
  StacksInterviewRoute: StacksInterviewRoute,
  TreesSplatRoute: TreesSplatRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
  ComplexityIndexRoute: ComplexityIndexRoute,
  GraphsIndexRoute: GraphsIndexRoute,
  PlaygroundsIndexRoute: PlaygroundsIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  LearnCourseLessonRoute: LearnCourseLessonRoute,
  LearnCourseIndexRoute: LearnCourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
