import type { HLesson } from "./types";

export const H_REVISION: HLesson[] = [
  {
    slug: "cheatsheet",
    title: "Complexity Cheat Sheet",
    eyebrow: "Review · 1",
    description: "Every heap operation and every complexity — the page you print before the interview.",
    difficulty: "Beginner",
    readMinutes: 3,
    sections: [
      { type: "heading", text: "Core operations" },
      { type: "complexity", rows: [
        { op: "peek",          time: "O(1)",       space: "O(1)" },
        { op: "push (insert)", time: "O(log n)",   space: "O(1)" },
        { op: "pop (extract)", time: "O(log n)",   space: "O(1)" },
        { op: "heapify one",   time: "O(log n)",   space: "O(1)" },
        { op: "build_heap",    time: "O(n)",       space: "O(1)" },
        { op: "heap sort",     time: "O(n log n)", space: "O(1)", note: "In-place, not stable." },
        { op: "search",        time: "O(n)",       space: "O(1)", note: "Heap doesn't help." },
        { op: "delete arbitrary", time: "O(n)",    space: "O(1)", note: "O(log n) if you keep an index map." },
      ]},
      { type: "heading", text: "Priority-queue patterns" },
      { type: "complexity", rows: [
        { op: "Dijkstra (V+E) log V",       time: "O((V + E) log V)", space: "O(V)" },
        { op: "Top-K over stream of n",     time: "O(n log k)",       space: "O(k)" },
        { op: "Median from stream (add)",   time: "O(log n)",         space: "O(n)" },
        { op: "Merge k sorted arrays (N)",  time: "O(N log k)",       space: "O(k)" },
      ]},
      { type: "heading", text: "Index math" },
      { type: "code", code: `parent(i) = (i - 1) // 2\nleft(i)   = 2 * i + 1\nright(i)  = 2 * i + 2\nlast_internal = n // 2 - 1` },
    ],
  },
  {
    slug: "memory-representation",
    title: "Memory Representation",
    eyebrow: "Review · 2",
    description: "The single picture that ties the array, the tree, and the index math together.",
    difficulty: "Beginner",
    readMinutes: 3,
    sections: [
      { type: "heapViz", data: [10, 20, 15, 30, 40, 50, 100, 25, 45], kind: "min",
        caption: "Read levels left-to-right; the array below is exactly what heapq stores." },
      { type: "indexDiagram", data: [10, 20, 15, 30, 40, 50, 100, 25, 45], focus: 3,
        caption: "For node at index 3 (value 30): parent lives at 1 (20), and its children live at 7 (25) and 8 (45)." },
      { type: "table", headers: ["Formula", "Result"], rows: [
        ["parent(i) = (i - 1) // 2", "Round-down division"],
        ["left(i) = 2i + 1",         "May be ≥ n → no child"],
        ["right(i) = 2i + 2",        "May be ≥ n → no child"],
        ["first_leaf = n // 2",       "Everything above sifts down"],
      ]},
    ],
  },
  {
    slug: "mistakes",
    title: "Common Mistakes",
    eyebrow: "Review · 3",
    description: "Every heap bug I have ever debugged. Read this before the interview.",
    difficulty: "Beginner",
    readMinutes: 4,
    sections: [
      { type: "mistakes", items: [
        "Confusing parent formulas: parent = (i − 1) // 2, NOT i // 2 for zero-indexed arrays.",
        "Sift-down that swaps with the wrong child — always pick the smaller child in a min-heap, not just any smaller child.",
        "Treating a heap like a sorted list — `for x in heap` gives heap order, not sorted order.",
        "Confusing heap with BST — heaps don't support O(log n) search; only the root is guaranteed extreme.",
        "Building a heap with n × push (O(n log n)) instead of heapify (O(n)).",
        "Forgetting to sift-down after pop — the tail value promoted to the root usually violates the invariant.",
        "Pushing tuples whose second element is a dict or a custom object without ordering — the priority tie crashes.",
        "Off-by-one in heap sort's shrinking boundary — pass the current `end`, not `len(a)`, to sift-down.",
        "Trying to update-key by mutating the value in place — the heap invariant no longer reflects reality.",
      ]},
    ],
  },
  {
    slug: "faq",
    title: "FAQ",
    eyebrow: "Review · 4",
    description: "The questions everyone asks the second time they see heaps.",
    difficulty: "Beginner",
    readMinutes: 5,
    sections: [
      { type: "faq", items: [
        { q: "Why must a heap be a complete binary tree?",
          a: "Completeness keeps the height at exactly ⌊log₂ n⌋ AND lets the tree pack contiguously into an array. If the tree had holes, the index formulas 2i+1 / 2i+2 could point to non-existent nodes and the array would waste space." },
        { q: "Heap vs BST — when does each win?",
          a: "Use a heap when you only need the extreme value repeatedly (priority queue). Use a BST when you also need ordered iteration, range queries, or arbitrary lookup. Heaps trade full ordering for cheaper storage and constant-factor speed on the operations they DO support." },
        { q: "Why use an array instead of pointers?",
          a: "The complete-tree shape means every level is fully packed, so pointer nodes would only add overhead. The array is cache-friendly, uses O(1) extra memory per element, and lets index arithmetic replace pointer chasing." },
        { q: "Why is build_heap O(n)?",
          a: "Bottom-up sift-down does at most h work at a node of height h. Roughly n/2^(h+1) nodes live at height h in a complete tree, so total work is Σ h · n/2^(h+1), a bounded geometric series that sums to O(n)." },
        { q: "Why isn't a heap fully sorted?",
          a: "Only the parent-child relationship is ordered; siblings and cousins are unrelated. A heap is a partial order, not a total order. If you need sorted output, run heap sort — it's the extraction sequence that produces the sort." },
        { q: "When should I NOT use a heap?",
          a: "Whenever you need arbitrary-value lookup, sorted iteration, or update-by-key. In those cases a balanced BST, a sorted container, or an indexed heap variant is the right tool." },
        { q: "Does Python have a max-heap?",
          a: "Not directly. Either negate values on top of `heapq`, wrap objects with an inverted __lt__, or write a MaxHeap class. See the Max Heap tier." },
        { q: "Is heap sort ever the right sort?",
          a: "It shines when you need guaranteed O(n log n) worst case with O(1) extra memory. It is not stable, so Python's Timsort (`sorted`) usually wins in practice." },
      ]},
    ],
  },
  {
    slug: "interview-questions",
    title: "Interview Questions",
    eyebrow: "Review · 5",
    description: "A tier-graded bank of the questions interviewers actually ask.",
    difficulty: "Intermediate",
    readMinutes: 5,
    sections: [
      { type: "heading", text: "Beginner" },
      { type: "interview", items: [
        "Define the heap property. How does it differ from the BST property?",
        "Write down the parent / left / right index formulas.",
        "How does a heap support O(1) peek but only O(log n) pop?",
        "Why does a heap need to be a complete binary tree?",
      ]},
      { type: "heading", text: "Intermediate" },
      { type: "interview", items: [
        "Implement heappush and heappop from scratch, iteratively.",
        "Show why building a heap is O(n), not O(n log n).",
        "Given a min-heap, how do you get the k largest elements without sorting?",
        "How do you implement a priority queue that supports items with equal priority?",
      ]},
      { type: "heading", text: "Advanced" },
      { type: "interview", items: [
        "How would you support decrease-key in O(log n)? (Answer: index map + sift-up.)",
        "Explain the two-heap median-of-stream technique and why the rebalance rule holds.",
        "Discuss the trade-offs between binary, d-ary (e.g. 4-ary), Fibonacci, and pairing heaps.",
        "Design a data structure that supports insert, pop-min, AND delete-by-value in O(log n).",
      ]},
      { type: "callout", kind: "interview", title: "Interviewer tips",
        text: "Interviewers often follow up with 'why is that O(...)?' — always be ready to justify heapify's O(n) with the geometric-series argument and priority-queue log-factors with tree-height reasoning." },
    ],
  },
  {
    slug: "practice",
    title: "Practice Problems",
    eyebrow: "Review · 6",
    description: "Every LeetCode heap problem worth doing, grouped by difficulty.",
    difficulty: "Intermediate",
    readMinutes: 4,
    sections: [
      { type: "practice", groups: [
        { level: "Beginner", items: [
          { title: "LC 703 · Kth Largest in Stream", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/", difficulty: "Easy", pattern: "Min-heap size k" },
          { title: "LC 1046 · Last Stone Weight", url: "https://leetcode.com/problems/last-stone-weight/", difficulty: "Easy", pattern: "Max-heap" },
          { title: "HackerRank · QHeap1", url: "https://www.hackerrank.com/challenges/qheap1/problem", difficulty: "Easy", pattern: "Structure" },
        ]},
        { level: "Intermediate", items: [
          { title: "LC 215 · Kth Largest in Array", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "Medium", pattern: "Top-K" },
          { title: "LC 347 · Top K Frequent Elements", url: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "Medium", pattern: "Top-K + counter" },
          { title: "LC 973 · K Closest Points to Origin", url: "https://leetcode.com/problems/k-closest-points-to-origin/", difficulty: "Medium", pattern: "Top-K by distance" },
          { title: "LC 621 · Task Scheduler", url: "https://leetcode.com/problems/task-scheduler/", difficulty: "Medium", pattern: "Max-heap + cooldown" },
          { title: "LC 1642 · Furthest Building You Can Reach", url: "https://leetcode.com/problems/furthest-building-you-can-reach/", difficulty: "Medium", pattern: "Greedy + heap" },
          { title: "LC 767 · Reorganize String", url: "https://leetcode.com/problems/reorganize-string/", difficulty: "Medium", pattern: "Max-heap by frequency" },
        ]},
        { level: "Advanced", items: [
          { title: "LC 23 · Merge k Sorted Lists", url: "https://leetcode.com/problems/merge-k-sorted-lists/", difficulty: "Hard", pattern: "K-way merge" },
          { title: "LC 295 · Find Median from Data Stream", url: "https://leetcode.com/problems/find-median-from-data-stream/", difficulty: "Hard", pattern: "Two heaps" },
          { title: "LC 480 · Sliding Window Median", url: "https://leetcode.com/problems/sliding-window-median/", difficulty: "Hard", pattern: "Two heaps + lazy delete" },
          { title: "LC 502 · IPO", url: "https://leetcode.com/problems/ipo/", difficulty: "Hard", pattern: "Two heaps" },
          { title: "LC 239 · Sliding Window Maximum", url: "https://leetcode.com/problems/sliding-window-maximum/", difficulty: "Hard", pattern: "Heap or monotonic deque" },
          { title: "GfG · Merge K Sorted Arrays", url: "https://www.geeksforgeeks.org/merge-k-sorted-arrays/", difficulty: "Medium", pattern: "K-way merge" },
        ]},
      ]},
    ],
  },
  {
    slug: "references",
    title: "References",
    eyebrow: "Review · 7",
    description: "Every source I trust for heaps, grouped by purpose.",
    difficulty: "Beginner",
    readMinutes: 2,
    sections: [
      { type: "heading", text: "Documentation" },
      { type: "references", items: [
        { label: "Python heapq — official docs", url: "https://docs.python.org/3/library/heapq.html" },
        { label: "GeeksforGeeks · Heap Data Structure", url: "https://www.geeksforgeeks.org/heap-data-structure/" },
        { label: "W3Schools · Python Heaps", url: "https://www.w3schools.com/python/ref_module_heapq.asp" },
        { label: "CP-Algorithms · Binary Heap", url: "https://cp-algorithms.com/data_structures/binary_heap.html" },
      ]},
      { type: "heading", text: "Learning resources" },
      { type: "references", items: [
        { label: "MIT OCW 6.006 · Heaps and Heap Sort", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-4-heaps-and-heap-sort/" },
        { label: "Princeton Algorithms · Priority Queues", url: "https://algs4.cs.princeton.edu/24pq/" },
        { label: "CLRS Chapter 6 · Heapsort", url: "https://mitpress.mit.edu/9780262046305/" },
      ]},
      { type: "heading", text: "Practice" },
      { type: "references", items: [
        { label: "LeetCode · Heap problems tag", url: "https://leetcode.com/tag/heap-priority-queue/" },
        { label: "HackerRank · Heap challenges", url: "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=heap" },
        { label: "NeetCode 150 · Heap section", url: "https://neetcode.io/roadmap" },
      ]},
    ],
  },
];
